import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {createDemo} from '../model.mjs';
import {initializeSources} from '../addon-model.mjs';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/d1832/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({channel:'chrome',headless:true});
try{const page=await browser.newPage({viewport:{width:1550,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const state=createDemo();initializeSources(state);state.configs=Array.from({length:120},(_,i)=>({...structuredClone(state.configs[0]),id:'batch'+i,name:'配置'+i}));
await page.goto('http://127.0.0.1:4196');await page.evaluate(s=>localStorage.setItem('diy-web-lite-prototype-v1',JSON.stringify(s)),state);await page.reload();await page.locator('[data-action="batch-open"]').click();await page.locator('#batch-scope').selectOption('selected');await page.locator('[data-config="batch0"]').check();await page.locator('[data-action="batch-next"]').click();await page.locator('[data-config="batch50"]').check();assert.ok((await page.locator('#batch-count').innerText()).includes('2 套'));await page.locator('#batch-mode').selectOption('add');await page.locator('#batch-slot').selectOption('风扇');await page.locator('#batch-new-query').fill('990018');await page.waitForTimeout(180);const option=await page.locator('#batch-new-select option').last().getAttribute('value');await page.locator('#batch-new-select').selectOption(option);await page.locator('#batch-qty').fill('3');await page.locator('[data-action="batch-preview"]').click();assert.ok((await page.locator('#batch-diff').innerText()).includes('将修改 2 套'));await page.screenshot({path:fileURLToPath(new URL('../verification/batch-preview.png',import.meta.url))});await page.locator('[data-action="batch-apply"]').click();let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('diy-web-lite-prototype-v1')));assert.equal(saved.configs.filter(c=>c.actualParts.some(p=>p.slot==='风扇')).length,2);assert.equal(saved.configs[50].actualParts.at(-1).qty,3);await page.reload();await page.locator('[data-action="batch-open"]').click();await page.locator('#batch-mode').selectOption('add');await page.locator('#batch-slot').selectOption('CPU');await page.locator('#batch-new-select').selectOption('0');await page.locator('[data-action="batch-preview"]').click();assert.ok((await page.locator('#toast').innerText()).includes('已有配件'));assert.equal(await page.locator('[data-action="batch-apply"]').isDisabled(),true);await page.locator('dialog [data-action="close"]').first().click();
await page.locator('#overview-rows [data-action="edit"]').first().click();await page.locator('[data-action="add-part"]').click();assert.equal(await page.locator('select[name="slot"] option').count(),5);await page.locator('select[name="slot"]').selectOption('配件1');await page.getByRole('button',{name:'添加并选择配件',exact:true}).click();await page.locator('#part-special-only').check();await page.locator('[data-action="choose-special"]').first().click();assert.ok((await page.locator('.parts-table').innerText()).includes('配件1'));await page.locator('[data-action="batch-open"]').click();await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS cross-page batch selection, preview/apply, exact targets, slot collision, refresh persistence, single add and mobile layout');}finally{await browser.close();}
