import {sourceFor,partAddons,checkOption,validateOptions,validateSource,sourceReferences,applySource,newOption} from './addon-model.mjs';

export function createAddonUI(api){
 const {esc,money,icon,button,openModal,closeModal,render,commit,edit,toast}=api;
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
 let context=null,costQuery='',slotFilter='',costPage=0,costEntries=[],costMatches=[],costShop,searchTimer;
 const costPageSize=50;
 let goodsIndex=[],goodsById=new Map();
 function indexGoods(){goodsIndex=state().catalog.map(p=>({p,search:(p.slot+' '+p.name+' '+p.goodsId).toLowerCase()}));goodsById=new Map(state().catalog.map(p=>[p.goodsId,p]));}
 function indexCosts(){const sid=api.shopId(),byGoods=new Map();if(costShop!==sid)costPage=0;costShop=sid;for(const source of state().sources){if(source.shopId!==sid)continue;const list=byGoods.get(source.goodsId)||[];list.push(source);byGoods.set(source.goodsId,list);}costEntries=state().catalog.flatMap(p=>{const sources=byGoods.get(p.goodsId)||[],fallback={sourceId:'lite-source:'+sid+':'+p.goodsId,shopId:sid,goodsId:p.goodsId,name:p.name,upgrade:'',addons:[]};return(state().cloud&&sources.length?sources:[sources.length===1?sources[0]:fallback]).map(source=>({p,source,search:[p.name,p.goodsId,source.name,source.upgrade,...source.addons.map(o=>o.text)].join(' ').toLowerCase()}));});}
 function costPagination(){const n=costMatches.length;return `<span>显示 ${n?costPage*costPageSize+1:0}–${Math.min(n,(costPage+1)*costPageSize)} / 共 ${n} 项 · 每页 ${costPageSize} 项</span><div>${button('上一页','addon-cost-prev','',costPage===0?'disabled':'')}<span> ${costPage+1} / ${Math.max(1,Math.ceil(n/costPageSize))} </span>${button('下一页','addon-cost-next','',(costPage+1)*costPageSize>=n?'disabled':'')}</div>`;}
 function refreshCosts(){if(!$('#cost-rows'))return;$('#cost-rows').innerHTML=costRows();$('#cost-pagination').innerHTML=costPagination();}
 function searchCosts(q){costQuery=q;costPage=0;clearTimeout(searchTimer);if(costEntries.length<200)refreshCosts();else searchTimer=setTimeout(refreshCosts,120);}
 const state=()=>api.state();
 const label=o=>`${o.priceCents===null?'价格待填':'+'+money(o.priceCents/100)} · ${o.text||'未命名加购'}`;
 function brief(options){return options.map(o=>`${label(o)}${o.enabled?'':'（不展示）'}；${o.mode==='add'?'额外加装':'替换原配件 × '+o.originalQty} → ${o.items.map(item=>(state().catalog.find(p=>p.goodsId===item.goodsId)?.name||item.goodsId)+' × '+item.qty).join(' + ')}`).join('；\n')||'暂无加购';}
 function block(part,index){
  if(!part.goodsId)return '';
  const data=partAddons(state(),api.shopId(),part),active=data.addons.filter(o=>o.enabled);
  return `<div class="part-addons"><div class="part-addon-heading"><span>${data.custom?'本配置自定义':data.unbound?'待绑定准确输出源':'跟随本店输出源'}</span>${button(data.addons.length?'编辑加购':'＋ 设置加购','addon-part','text-button',`data-index="${index}"`)}</div>${data.upgrade?`<p class="part-upgrade">${esc(data.upgrade)}</p>`:''}${active.map(o=>`<div class="addon-line"><strong>${o.priceCents===null?'待填价':'+'+money(o.priceCents/100)}</strong><span>${esc(o.text)}</span></div>`).join('')}${!active.length&&data.addons.length?'<small>已保存的方案均设为不展示</small>':''}</div>`;
 }
 function costRows(q=costQuery){costQuery=q;const query=q.trim().toLowerCase();costMatches=costEntries.filter(({p,search})=>(!slotFilter||p.slot===slotFilter)&&search.includes(query));costPage=Math.min(costPage,Math.max(0,Math.ceil(costMatches.length/costPageSize)-1));return costMatches.slice(costPage*costPageSize,(costPage+1)*costPageSize).map(({p,source})=>{const active=source.addons.filter(o=>o.enabled);return `<tr><td><strong>${esc(source.name)}</strong><small class="part-id">${state().cloud?'商品':'示例'} ID ${esc(p.goodsId)}${state().cloud?'<br>来源 '+esc(source.sourceId):''}</small>${source.upgrade?`<small class="source-upgrade">${esc(source.upgrade)}</small>`:''}</td><td>${esc(p.slot)}</td><td class="money">${money(p.erp)}</td><td class="money">${money(p.tax)}</td><td>${p.stockAvailable??'未知'}</td><td class="source-addon-cell">${active.map(o=>`<div><b>${o.priceCents===null?'待填价':'+'+money(o.priceCents/100)}</b><span>${esc(o.text)}</span></div>`).join('')||'<span class="muted">未设置</span>'}${source.addons.length>active.length?`<small class="muted">另有 ${source.addons.length-active.length} 条不展示</small>`:''}</td><td><div class="source-row-actions">${button('维护输出源','addon-source','text-button',`data-id="${esc(p.goodsId)}" data-source="${esc(source.sourceId)}"`)}${button('编辑核算价','edit-cost','text-button',`data-id="${esc(p.goodsId)}"`)}</div></td></tr>`;}).join('')||'<tr><td colspan="7" class="empty">没有找到商品或加购方案</td></tr>';}
 function costsPage(){indexCosts();return `<div class="page-heading"><div><div class="breadcrumb">三店共用核算价 / 各店输出源</div><h1>核算价格 <span class="heading-tag">输出源维护</span></h1><p>维护配件显示名称、升级说明和加购方案，加购价格与对应商品放在一起核对。</p></div></div><div class="source-scope-bar"><label>当前输出源店铺 <select id="source-shop">${state().shops.map(s=>`<option value="${s.id}" ${api.shopId()===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><span>核算单价三店共用 · 名称、升级说明与加购按店铺维护</span></div><section class="panel"><div class="panel-toolbar"><div class="toolbar-left"><label class="search">${icon('search')}<input id="cost-query" placeholder="搜索型号、ID 或加购文案" aria-label="搜索核算商品" value="${esc(costQuery)}"></label><select id="source-slot" aria-label="配件类型"><option value="">全部配件</option>${[...new Set(state().catalog.map(p=>p.slot))].map(s=>`<option ${slotFilter===s?'selected':''}>${esc(s)}</option>`).join('')}</select></div><span class="muted">${state().catalog.length} 个${state().cloud?'云端':'示例'}商品 · ERP 单价只读</span></div><div class="table-scroll"><table class="source-table"><thead><tr><th>本店显示名称 / 商品 ID</th><th>类型</th><th>ERP 单价</th><th>核算单价</th><th>可销库存</th><th>对应加购方案</th><th>操作</th></tr></thead><tbody id="cost-rows">${costRows()}</tbody></table></div><div id="cost-pagination" class="table-footer list-pagination">${costPagination()}</div></section><p class="source-footnote">加购方案是可选报价，不自动增加整机成本或售价；差价单独核对。配件行可以跟随本店输出源，或另存为当前配置的自定义加购。</p>`;}
 function startSource(id,sourceId){indexGoods();const p=state().catalog.find(p=>p.goodsId===id);context={kind:'source',partIndex:null,source:structuredClone(sourceFor(state(),api.shopId(),id,sourceId)),row:p};draw();}
 function startPart(index){indexGoods();const part=api.current().actualParts[index],source=sourceFor(state(),api.shopId(),part.goodsId,part.sourceId),data=partAddons(state(),api.shopId(),part);
  if(state().cloud&&source.unbound)throw Error('此配件尚未绑定唯一输出源，请重新选择配件来源');context={kind:'part',partIndex:index,configId:api.current().id,partId:part.lineId,goodsId:part.goodsId,row:state().catalog.find(p=>p.goodsId===part.goodsId),source:{...structuredClone(source),addons:data.addons,upgrade:data.upgrade},wasCustom:data.custom};draw();
 }
 function currentPart(){const c=api.current();const p=c?.actualParts[context.partIndex];if(c?.id!==context.configId||p?.lineId!==context.partId||p?.goodsId!==context.goodsId)throw Error('配置配件已经变化，请重新打开加购编辑');return p;}
 function goodsOptions(selected,q=''){const query=q.trim().toLowerCase(),items=[];for(const entry of goodsIndex){if(entry.search.includes(query)){items.push(entry.p);if(items.length>=60)break;}}if(selected&&!items.some(p=>p.goodsId===selected))items.unshift(goodsById.get(selected)||{goodsId:selected,slot:'原商品',name:'未在目录中'});return `<option value="">选择准确商品</option>`+items.map(p=>`<option value="${esc(p.goodsId)}" ${selected===p.goodsId?'selected':''}>${esc(p.slot+' · '+p.name+' ['+p.goodsId+']')}</option>`).join('');}
 function optionCard(o,i){return `<section class="addon-edit-card" data-option-index="${i}"><div class="addon-card-title"><strong>加购方案 ${i+1}</strong><label><input type="checkbox" data-addon-field="enabled" ${o.enabled?'checked':''}> 在配件行展示</label>${button('移除方案','addon-remove-option','text-button',`data-index="${i}"`)}</div><div class="addon-option-fields"><label class="addon-description">加购文案<input data-addon-field="text" required maxlength="160" value="${esc(o.text)}" placeholder="例如：升级 2TB 高速固态硬盘"></label><label>加购总价（元）<input data-addon-field="price" type="number" min="0" step="0.01" ${!state().cloud||o.items.length?'required':''} value="${o.priceCents===null?'':o.priceCents/100}" placeholder="填写金额"></label><label>加购方式<select data-addon-field="mode"><option value="replace" ${o.mode==='replace'?'selected':''}>替换原配件</option><option value="add" ${o.mode==='add'?'selected':''}>额外加装</option></select></label><label>替换原配件数量<input data-addon-field="originalQty" type="number" min="1" max="100000" step="1" value="${esc(o.originalQty)}" ${o.mode==='add'?'disabled':''} required></label></div><div class="addon-item-heading"><strong>关联的新商品</strong><span>组合中每项单独计成本，加购总价只收一次</span></div><div class="addon-items">${o.items.map((item,j)=>`<div class="addon-item" data-item-index="${j}"><label>商品<input data-addon-search placeholder="搜索全部商品：型号 / ID" aria-label="搜索加购商品"><small class="muted">最多显示 60 个匹配商品，已选商品始终保留</small><select data-addon-item="goodsId" required>${goodsOptions(item.goodsId)}</select></label><label>数量<input data-addon-item="qty" type="number" min="1" max="100000" step="1" required value="${esc(item.qty??'')}"></label>${button(icon('x'),'addon-remove-item','icon-button',`data-index="${i}" data-item="${j}" aria-label="移除方案${i+1}的商品${j+1}"`)}</div>`).join('')}</div>${button('+ 添加组合商品','addon-add-item','text-button',`data-index="${i}"`)}<div class="addon-check" data-check="${i}"></div></section>`;}
 function draw(){
  const ctx=context,p=ctx.row||{name:ctx.source.name,goodsId:ctx.goodsId,erp:null,tax:null},refs=sourceReferences(state(),ctx.source),isSource=ctx.kind==='source';
  openModal(isSource?'维护本店输出源':'编辑配件加购',`<div class="source-editor-meta"><div><strong>${esc(p.name)}</strong><small>商品 ID ${esc(p.goodsId)} · ${esc(state().shops.find(s=>s.id===ctx.source.shopId)?.name)}</small></div><div><span>ERP ${money(p.erp)}</span><span>核算 ${money(p.tax)}</span></div></div><div class="notice-box">${isSource?`保存后更新本店 ${refs.inherited} 套跟随输出源的配置；${refs.custom} 套有自定义加购的配置保留原设置。`:'保存为当前配置的自定义加购，不修改其他配置或本店输出源。原配件、整机售价及成本保持不变。'}</div>${isSource?`<label class="block-label">本店产品显示名称<input id="source-name" required maxlength="160" value="${esc(ctx.source.name)}"></label>`:''}<label class="block-label">升级说明（选填）<input id="source-upgrade" maxlength="200" value="${esc(ctx.source.upgrade)}" placeholder="例如：支持升级 64GB 内存 / 2TB 固态"></label><div class="addon-list-heading"><h3>对应加购方案 <small>${ctx.source.addons.length} 条</small></h3>${button('+ 新增加购','addon-add-option')}</div><div id="addon-options">${ctx.source.addons.map(optionCard).join('')||'<div class="empty compact">还没有加购方案，点击「新增加购」开始。</div>'}</div><p class="addon-formula">差价 = 原配件成本 × 替换数量 + 加购总价 − 新组合成本。额外加装不抵扣原配件成本；缺失成本显示“待补充”，不当作零成本。</p>${!isSource?`<div class="addon-inheritance"><span>${ctx.wasCustom?'当前有独立加购设置':'当前跟随本店输出源'}</span>${button('恢复跟随输出源','addon-inherit','text-button')}</div>`:''}`,`<button type="submit" class="primary">${isSource?'预览并保存输出源':'保存本配置加购'}</button>`,()=>save());
  $('#modal').classList.add('addon-dialog');refreshChecks();
 }
 function read(){
  if(!context||!$('#addon-options'))return;
  if($('#source-name'))context.source.name=$('#source-name').value.trim();context.source.upgrade=$('#source-upgrade').value.trim();
  context.source.addons=$$('[data-option-index]').map(card=>{const old=context.source.addons[Number(card.dataset.optionIndex)],get=k=>card.querySelector(`[data-addon-field="${k}"]`),price=get('price').value;return {...old,text:get('text').value.trim(),enabled:get('enabled').checked,mode:get('mode').value,priceCents:price===''?null:/^\d+(\.\d{1,2})?$/.test(price)?Math.round(Number(price)*100):NaN,originalQty:Number(get('originalQty').value),items:[...card.querySelectorAll('[data-item-index]')].map(row=>({goodsId:row.querySelector('[data-addon-item="goodsId"]').value,qty:Number(row.querySelector('[data-addon-item="qty"]').value)}))};});
 }
 function refreshChecks(){if(!context||!$('#addon-options'))return;read();context.source.addons.forEach((o,i)=>{const result=checkOption(state(),context.source,o);$(`[data-check="${i}"]`).innerHTML=result.fields.map(f=>`<span>${f.label} 差价 <strong class="${f.diffCents===null?'incomplete':f.diffCents<0?'negative':'positive'}">${f.diffCents===null?'待补充':money(f.diffCents/100)}</strong></span>`).join('')+(result.reason?`<small>${esc(result.reason)}</small>`:'');});}
 function save(){read();const ctx=context;validateOptions(ctx.source.addons,state().catalog,{allowDisplayOnly:!!state().cloud});
  if(ctx.kind==='part'){currentPart();edit(c=>{c.actualParts[ctx.partIndex].addonOverride={goodsId:ctx.goodsId,upgrade:ctx.source.upgrade,addons:structuredClone(ctx.source.addons)};});closeModal();render();toast('加购已写入当前配置草稿，请保存配置');context=null;return;}
  validateSource(state(),ctx.source);const source=structuredClone(ctx.source),before=structuredClone(sourceFor(state(),source.shopId,source.goodsId,source.sourceId)),refs=sourceReferences(state(),source);
  openModal('确认输出源修改',`<p class="modal-intro">${esc(state().shops.find(s=>s.id===source.shopId).name)} · 商品 ID ${source.goodsId}</p><div class="table-scroll"><table class="diff-table"><thead><tr><th>字段</th><th>修改前</th><th>修改后</th></tr></thead><tbody><tr><td>显示名称</td><td>${esc(before.name)}</td><td>${esc(source.name)}</td></tr><tr><td>升级说明</td><td>${esc(before.upgrade||'无')}</td><td>${esc(source.upgrade||'无')}</td></tr><tr><td>加购方案</td><td>${esc(brief(before.addons))}</td><td>${esc(brief(source.addons))}</td></tr></tbody></table></div><p class="warning">本店 ${refs.inherited} 套配置跟随更新，${refs.custom} 套自定义配置保留。其他店铺、ERP 成本及核算单价不变。</p>`,button('返回编辑','addon-back')+'<button class="primary" type="submit">确认保存输出源</button>',()=>{
   if(JSON.stringify(sourceFor(state(),source.shopId,source.goodsId,source.sourceId))!==JSON.stringify(before))throw Error('输出源已经变化，请重新预览');commit('维护本店输出源：'+source.name,()=>applySource(state(),source));closeModal();context=null;render();toast('输出源已保存，跟随配置的加购已更新');
  });
 }
 function actions(action,data){if(!action.startsWith('addon-'))return false;
  if(action==='addon-cost-prev'||action==='addon-cost-next'){costPage=Math.max(0,costPage+(action==='addon-cost-next'?1:-1));refreshCosts();return true;}
  if(action==='addon-source'){startSource(data.id,data.source);return true;}if(action==='addon-part'){startPart(Number(data.index));return true;}if(!context)throw Error('请重新打开加购编辑');
  if(action==='addon-back'){draw();return true;}
  if(action==='addon-inherit'){currentPart();const ctx=context;openModal('恢复跟随本店输出源',`<p class="modal-intro">当前配件的自定义加购将替换为本店输出源的方案。只改变当前配置草稿，保存前可以撤销。</p>`,button('返回编辑','addon-back')+'<button class="primary" type="submit">确认恢复跟随</button>',()=>{currentPart();edit(c=>delete c.actualParts[ctx.partIndex].addonOverride);closeModal();context=null;render();toast('当前配件已恢复跟随本店输出源');});return true;}
  read();const i=Number(data.index);if(action==='addon-add-option'){if(context.source.addons.length>=30)throw Error('最多添加 30 个加购方案');context.source.addons.push(newOption());}
  else if(action==='addon-remove-option')context.source.addons.splice(i,1);
  else if(action==='addon-add-item'){if(context.source.addons[i].items.length>=100)throw Error('一个组合最多 100 个商品');context.source.addons[i].items.push({goodsId:'',qty:1});}
  else if(action==='addon-remove-item')context.source.addons[i].items.splice(Number(data.item),1);
  draw();return true;
 }
 $('#modal').addEventListener('input',e=>{if(e.target.matches('[data-addon-search]')){const input=e.target;clearTimeout(input.searchTimer);input.searchTimer=setTimeout(()=>{if(!input.isConnected)return;const select=input.closest('label').querySelector('select');select.innerHTML=goodsOptions(select.value,input.value);},120);return;}if(e.target.matches('[data-addon-field],[data-addon-item]'))refreshChecks();});
 $('#modal').addEventListener('change',e=>{if(e.target.matches('[data-addon-field="mode"]')){const card=e.target.closest('[data-option-index]');card.querySelector('[data-addon-field="originalQty"]').disabled=e.target.value==='add';}if(e.target.matches('[data-addon-field],[data-addon-item]'))refreshChecks();});
 $('#modal').addEventListener('close',()=>$('#modal').classList.remove('addon-dialog'));
 $('#app').addEventListener('change',e=>{if(e.target.id==='source-shop'){api.selectShop(e.target.value);render();}if(e.target.id==='source-slot'){slotFilter=e.target.value;costPage=0;refreshCosts();}});
 return {block,costsPage,costRows,searchCosts,actions};
}
