import {actualParts} from '../prototype/actual-parts.js';
import {slots} from '../prototype/core.js';
import {batchCatalog,partKey,planParts} from './batch-parts.mjs';
export function createBatchUI(api){
 const {esc,button,openModal,closeModal,toast}=api,$=s=>document.querySelector(s);let ctx;
 function open(){const state=api.state(),shopId=api.shopId(),products=new Map(state.products.filter(p=>p.shopId===shopId).map(p=>[p.id,p]));
 const configs=state.configs.filter(c=>products.has(c.productId)).map(base=>({...structuredClone(state.drafts[base.id]||base),shopId,product:products.get(base.productId).name}));
 if(!configs.length)throw Error('本店暂无配置');
 ctx={shopId,configs,catalog:batchCatalog(state,shopId),selected:new Set(),page:0,query:'',mode:'replace',scope:'link',key:'',row:null,slot:'配件1',qty:'',plan:null};
 openModal('批量修改 / 添加配件',`<p class="notice-box">修改实际配件，先预览后统一保存。已选配置的现有草稿会一并保存。</p><div class="form-grid two"><label>修改范围<select id="batch-scope"><option value="link">当前链接全部配置</option><option value="selected">勾选本店配置（可跨链接）</option><option value="shop">本店全部配置</option></select></label><label>操作<select id="batch-mode"><option value="replace">查找替换配件</option><option value="add">一键添加配件</option></select></label></div><section id="batch-selection" hidden><label class="search"><input id="batch-config-search" placeholder="搜索链接 / 配置名称"></label><label class="special-only"><input id="batch-all" type="checkbox"> 全选搜索结果（包含其他页）</label><div id="batch-configs"></div><div id="batch-pages" class="list-pagination"></div></section><p id="batch-count" class="muted"></p><div id="batch-old"><label class="block-label">查找原配件<input id="batch-old-query" placeholder="搜索已用配件名称或商品 ID"><select id="batch-old-select" aria-label="原配件"></select></label></div><label class="block-label">新配件<input id="batch-new-query" placeholder="搜索本店全部配件 / 特殊配件"><select id="batch-new-select" aria-label="新配件"></select><small class="muted">最多显示 60 项，搜索覆盖全部商品与特殊配件</small></label><div id="batch-stock" class="notice-box" aria-live="polite">选择新配件后查看可销库存与单价</div><div class="form-grid two"><label id="batch-slot-label" hidden>添加到槽位<select id="batch-slot">${slots.map(s=>`<option ${s==='配件1'?'selected':''}>${s}</option>`).join('')}</select></label><label>数量<input id="batch-qty" type="number" min="1" max="100000" step="1" placeholder="替换时留空保留原数量"></label></div><div class="actions">${button('预览修改','batch-preview','primary')}</div><div id="batch-diff"></div>`,button('确认保存批量修改','batch-apply','primary','disabled'));
 $('#batch-scope').onchange=e=>{ctx.scope=e.target.value;$('#batch-selection').hidden=ctx.scope!=='selected';invalidate();drawTargets();drawOld();};
 $('#batch-mode').onchange=e=>{ctx.mode=e.target.value;$('#batch-old').hidden=ctx.mode==='add';$('#batch-slot-label').hidden=ctx.mode!=='add';if(ctx.mode==='add'&&!ctx.qty){ctx.qty='1';$('#batch-qty').value='1';}invalidate();};
 for(const [id,field] of [['batch-qty','qty'],['batch-slot','slot']])$('#'+id).oninput=e=>{ctx[field]=e.target.value;invalidate();};
 let timer;for(const id of ['batch-config-search','batch-old-query','batch-new-query'])$('#'+id).oninput=e=>{const input=e.target;clearTimeout(timer);timer=setTimeout(()=>{if(!input.isConnected)return;if(id==='batch-config-search'){ctx.query=input.value.toLowerCase();ctx.page=0;drawTargets();}else if(id==='batch-old-query')drawOld();else drawNew();},120);};
 $('#batch-all').onchange=e=>{for(const c of matches())e.target.checked?ctx.selected.add(c.id):ctx.selected.delete(c.id);invalidate();drawTargets();drawOld();};
 $('#batch-old-select').onchange=e=>{ctx.key=e.target.value;invalidate();};$('#batch-new-select').onchange=e=>{ctx.row=e.target.value===''?null:ctx.catalog[Number(e.target.value)];invalidate();drawStock();};
 $('#batch-configs').onchange=e=>{if(!e.target.dataset.config)return;e.target.checked?ctx.selected.add(e.target.dataset.config):ctx.selected.delete(e.target.dataset.config);invalidate();drawTargets();drawOld();};
 drawTargets();drawOld();drawNew();
 }
 function targets(){return ctx.configs.filter(c=>ctx.scope==='shop'||ctx.scope==='link'&&c.productId===api.productId()||ctx.scope==='selected'&&ctx.selected.has(c.id));}
 function matches(){return ctx.configs.filter(c=>(c.product+' '+c.name).toLowerCase().includes(ctx.query));}
 function invalidate(){ctx.plan=null;$('#batch-diff').innerHTML='';$('[data-action="batch-apply"]').disabled=true;}
 function drawTargets(){const list=matches(),selected=list.filter(c=>ctx.selected.has(c.id)).length;$('#batch-all').checked=!!list.length&&selected===list.length;$('#batch-all').indeterminate=selected>0&&selected<list.length;$('#batch-configs').innerHTML=list.slice(ctx.page*50,ctx.page*50+50).map(c=>`<label class="batch-target"><input type="checkbox" data-config="${esc(c.id)}" ${ctx.selected.has(c.id)?'checked':''}><span>${esc(c.product)} / <strong>${esc(c.name)}</strong></span></label>`).join('');$('#batch-pages').innerHTML=`<span>共 ${list.length} 套 · 已勾选 ${ctx.selected.size} 套</span>${button('上一页','batch-prev','',ctx.page?'':'disabled')}${button('下一页','batch-next','',(ctx.page+1)*50>=list.length?'disabled':'')}`;$('#batch-count').textContent=`当前范围 ${targets().length} 套配置`;
 }
 function options(entries,selected,value,label){const limited=entries.slice(0,60);const chosen=entries.find(e=>value(e)===selected);if(chosen&&!limited.includes(chosen))limited.unshift(chosen);return '<option value="">请选择</option>'+limited.map(e=>`<option value="${esc(value(e))}" ${value(e)===selected?'selected':''}>${esc(label(e))}</option>`).join('');}
 function drawOld(){const map=new Map();for(const c of targets())for(const p of actualParts(c))if(p.name)map.set(partKey(p),p);if(ctx.key&&!map.has(ctx.key)){ctx.key='';invalidate();}const q=$('#batch-old-query').value.toLowerCase(),entries=[...map].filter(([key,p])=>(p.name+' '+p.goodsId).toLowerCase().includes(q)||key===ctx.key);$('#batch-old-select').innerHTML=options(entries,ctx.key,e=>e[0],e=>e[1].name+(e[1].goodsId?' ['+e[1].goodsId+']':' · 特殊 / 未绑定'));}
 function drawNew(){const selected=ctx.row?String(ctx.catalog.indexOf(ctx.row)):'',q=$('#batch-new-query').value.toLowerCase(),entries=ctx.catalog.flatMap((p,i)=>p.search.includes(q)||String(i)===selected?[{p,i}]:[]);$('#batch-new-select').innerHTML=options(entries,selected,e=>String(e.i),e=>e.p.name+(e.p.specialComponent?' · 特殊配件，仅显示':' ['+e.p.goodsId+']')+(e.p.sourceId?' · '+e.p.sourceId:'')+' · 库存 '+(e.p.specialComponent?'不适用':e.p.stockAvailable??'未知'));}
 function drawStock(){const p=ctx.row;if(!p){$('#batch-stock').textContent='选择新配件后查看可销库存与单价';return;}const cost=v=>v==null?'未知':'¥'+Number(v).toFixed(2);$('#batch-stock').innerHTML=p.specialComponent?'<strong>特殊配件</strong> · 仅显示，不计成本；库存不适用':`<strong>${esc(p.name)}</strong><p>可销库存：<strong>${esc(p.stockAvailable??'未知')}</strong> · ERP 单价：${esc(cost(p.erp))} · 核算单价：${esc(cost(p.tax))}</p><small>库存按商品 ID ${esc(p.goodsId)} 匹配${p.stockAvailable==null?'，尚未读取 ERP 库存':''}</small>`;}
 async function actions(action){if(!action.startsWith('batch-'))return false;if(action==='batch-open'){open();return true;}if(!ctx)throw Error('请重新打开批量修改');
 if(action==='batch-prev'||action==='batch-next'){ctx.page+=action==='batch-next'?1:-1;drawTargets();return true;}
 if(action==='batch-preview'){invalidate();if(!targets().length)throw Error('请先选择目标配置');ctx.plan=planParts(targets(),{...ctx,qty:ctx.qty===''?null:Number(ctx.qty)});if(!ctx.plan.length)throw Error('没有需要修改的配件');ctx.pageDiff=0;drawDiff();$('[data-action="batch-apply"]').disabled=false;return true;}
 if(action==='batch-diff-prev'||action==='batch-diff-next'){ctx.pageDiff+=action==='batch-diff-next'?1:-1;drawDiff();return true;}
 if(action==='batch-apply'){if(!ctx.plan)throw Error('请先预览修改');await api.apply(ctx.plan);closeModal();api.render();toast(`已保存 ${ctx.plan.length} 套配置的配件修改`);ctx=null;return true;}return false;
 }
 function drawDiff(){const plan=ctx.plan;$('#batch-diff').innerHTML=`<h3>将修改 ${plan.length} 套配置</h3><p class="muted">原数量默认保留；不会覆盖已有槽位。确认后保存到浏览器，可在右上角同步云端。</p>${plan.slice(ctx.pageDiff*50,ctx.pageDiff*50+50).map(c=>`<div class="batch-diff-row"><strong>${esc(c.before.product)} / ${esc(c.before.name)}</strong>${c.diffs.map(d=>`<p>${esc(d.slot)}：${esc(d.before)} → <b>${esc(d.after)}</b></p>`).join('')}</div>`).join('')}<div class="list-pagination"><span>第 ${ctx.pageDiff+1} / ${Math.ceil(plan.length/50)} 页</span>${button('上一页','batch-diff-prev','',ctx.pageDiff?'':'disabled')}${button('下一页','batch-diff-next','',(ctx.pageDiff+1)*50>=plan.length?'disabled':'')}</div>`;}
 return {open,actions};
}
