import {receiveErpWindow} from './erp-window-bridge.mjs';
import script from './erp-script-text.mjs';
import {validateWebSnapshot,applyErpSnapshot} from './erp-data.mjs';
export function createWebErp(api){const {esc,openModal,button,download}=api,$=s=>document.querySelector(s);let stopReceive=null;let preview=null,mode='browser-script',timer,busy=false,diffPage=0,differences=[];
 const fmt=v=>v==null?'未知':String(v);
 function message(text){const el=$('#erp-message');if(el)el.textContent=text;}
 function open(){stopReceive?.();stopReceive=null;clearTimeout(timer);busy=false;preview=null;const snap=api.state().erpSnapshot;
 openModal('ERP 同步 · 库存与成本',`<label class="block-label">同步方式<select id="erp-mode"><option value="browser-script">网页脚本采集</option><option value="company-sql">公司数据库（SQL 同步）</option></select></label><p class="notice-box">先读取或导入并预览，再确认应用。按商品 ID 更新三店 ERP 成本与可销库存，人工核算价保持不变。</p><section id="erp-browser"><ol class="erp-steps"><li>下载并安装工作台 ERP 同步脚本（脚本猫 / 油猴）。</li><li>ERP 打开“分库库存”，选择“公司大库”，显示成本单价列。</li><li>脚本菜单选择“连接库存与成本同步”，核对顶栏姓名和成本列。</li><li>点击“打开 ERP 并接收”，在新开的 ERP 页面进入分库库存，再点“发送到工作台”。</li></ol><button type="button" id="erp-direct" class="primary">打开 ERP 并接收</button>${button('下载工作台 ERP 脚本','web-erp-offline')}<p class="muted">库存直接传给当前工作台页面，无需复制或下载文件。请将脚本更新至 0.2.3。</p><details><summary>备用：粘贴数据或导入文件</summary><label class="block-label">粘贴 ERP 库存数据<textarea id="erp-paste" rows="3" placeholder="在这里按 Ctrl+V（Mac 用 Command+V）"></textarea></label><button type="button" id="erp-paste-preview">粘贴数据并预览</button><details><summary>备用：导入快照文件</summary><label class="block-label">选择 ERP 库存快照<input id="erp-file" type="file" accept=".json,application/json"></label></details></details></section><section id="erp-sql" hidden><p class="muted">当前电脑的本地连接程序在公司局域网内直连数据库，只读“公司大库”的分库可销数和库存成本。密码仅用于本次连接，不写入缓存文件。</p><div class="form-grid two">${[['server','服务器'],['port','端口'],['database','数据库'],['user','只读账号']].map(([key,label])=>`<label>${label}<input id="erp-sql-${key}" ${key==='port'?'type="number" value="1433" min="1" max="65535"':'autocomplete="off"'}></label>`).join('')}<label class="span-all">密码<input id="erp-sql-password" type="password" autocomplete="off"></label></div><label class="special-only"><input id="erp-sql-encrypt" type="checkbox" checked>加密连接</label><label class="special-only"><input id="erp-sql-trust" type="checkbox">信任服务器证书（公司自签证书）</label>${button('读取 SQL 并预览','web-erp-sql','primary')}</section><p>${snap?'当前快照：'+esc(snap.source==='company-sql'?'SQL 公司大库':snap.account+' · 公司大库')+' · '+esc(new Date(snap.capturedAt).toLocaleString()):'尚未应用 ERP 库存快照'}</p>${button('读取本机 SQL 缓存','web-erp-cache','text-button')}<p id="erp-message" role="status"></p><div id="erp-preview"></div>`,button('确认应用库存与成本','web-erp-apply','primary','disabled'));
 $('#erp-mode').value=mode;$('#erp-mode').onchange=e=>{mode=e.target.value;$('#erp-browser').hidden=mode!=='browser-script';$('#erp-sql').hidden=mode!=='company-sql';};$('#erp-mode').onchange({target:$('#erp-mode')});
 $('#erp-direct').onclick=()=>{stopReceive?.();preview=null;$('[data-action="web-erp-apply"]').disabled=true;$('#erp-preview').innerHTML='';const panel=$('#erp-browser');try{stopReceive=receiveErpWindow({isActive:()=>panel.isConnected&&!panel.hidden,onSnapshot:showPreview,onStatus:message});}catch(error){message(error.message);}};
 $('#erp-paste-preview').onclick=()=>{preview=null;$('[data-action="web-erp-apply"]').disabled=true;$('#erp-preview').innerHTML='';try{const input=$('#erp-paste'),raw=input.value.trim();if(!raw)throw Error('请先在 ERP 页面复制库存，再粘贴到这里');if(new Blob([raw]).size>50000000)throw Error('数据超过 50 MB');showPreview(JSON.parse(raw));input.value='';}catch(error){message(error instanceof SyntaxError?'粘贴内容不是有效的 ERP 数据，请重新复制':error.message);}};
 $('#erp-file').onchange=async e=>{const input=e.target;preview=null;$('[data-action="web-erp-apply"]').disabled=true;try{const file=input.files[0];if(!file)return;if(file.size>50000000)throw Error('文件超过 50 MB');const data=JSON.parse(await file.text());if(input.isConnected)showPreview(data);}catch(error){message(error.message);}};
 }
 function showPreview(data){validateWebSnapshot(data);preview=data;diffPage=0;const map=new Map(data.rows.map(r=>[r.goodsId,r]));differences=api.state().catalog.flatMap(p=>{const row=map.get(p.goodsId),erp=row?.erp??null,stock=row?.stockAvailable??null;return p.erp!==erp||p.stockAvailable!==stock?[{name:p.name,id:p.goodsId,before:`${fmt(p.stockAvailable)} / ${fmt(p.erp)}`,after:`${fmt(stock)} / ${fmt(erp)}`}]:[];});drawPreview();$('[data-action="web-erp-apply"]').disabled=false;message('读取完成，核对差异后确认应用。缓存不代表已应用。');}
 function drawPreview(){const data=preview,old=api.state().erpSnapshot,source=data.source==='company-sql'?`${data.sqlSource?.server}:${data.sqlSource?.port} / ${data.sqlSource?.database}`:data.account;$('#erp-preview').innerHTML=`<div class="notice-box"><strong>${esc(source)} · 公司大库</strong><p>采集时间：${esc(new Date(data.capturedAt).toLocaleString())} · 成本列：${esc(data.costHeader)}</p><p>完整读取 ${data.total} 条，${differences.length} 个商品成本或库存变化。未匹配和空值显示未知，不当作零。</p>${old&&(old.account!==data.account||old.depotId!==data.depotId||old.costField!==data.costField||old.source!==data.source)?'<p class="warning">来源与上次不同，请核对账号、仓库和成本列。</p>':''}${old&&Date.parse(old.capturedAt)>Date.parse(data.capturedAt)?'<p class="warning">本次快照比当前数据更旧。</p>':''}</div><div class="table-scroll"><table class="diff-table"><thead><tr><th>商品 / ID</th><th>原库存 / ERP 成本</th><th>新库存 / ERP 成本</th></tr></thead><tbody>${differences.slice(diffPage*50,diffPage*50+50).map(d=>`<tr><td>${esc(d.name)}<small>${esc(d.id)}</small></td><td>${esc(d.before)}</td><td>${esc(d.after)}</td></tr>`).join('')||'<tr><td colspan="3">无成本或库存差异</td></tr>'}</tbody></table></div><div class="list-pagination"><span>第 ${diffPage+1} / ${Math.max(1,Math.ceil(differences.length/50))} 页</span>${button('上一页','web-erp-prev','',diffPage?'':'disabled')}${button('下一页','web-erp-next','',(diffPage+1)*50>=differences.length?'disabled':'')}</div>`;}
 async function actions(action){if(action==='web-erp-offline'){download(script,'workbench-erp.user.js');return true;}if(action==='web-erp-prev'||action==='web-erp-next'){diffPage+=action==='web-erp-next'?1:-1;drawPreview();return true;}if(busy)throw Error('正在读取库存，请等待完成');
 if(action==='web-erp-cache'){const {snapshot}=await api.request('snapshot');if(!snapshot)throw Error('本机暂无 SQL 缓存，请先读取');showPreview(snapshot);return true;}
 if(action==='web-erp-sql'){const panel=$('#erp-message');const settings=Object.fromEntries(['server','port','database','user'].map(k=>[k,$('#erp-sql-'+k).value]));settings.encrypt=$('#erp-sql-encrypt').checked;settings.trustServerCertificate=$('#erp-sql-trust').checked;let password=$('#erp-sql-password').value;$('#erp-sql-password').value='';busy=true;preview=null;$('[data-action="web-erp-apply"]').disabled=true;message('正在连接公司 SQL 并读取，最多等待 90 秒…');try{const {snapshot}=await api.request('sql-preview',{settings,password});if(panel.isConnected)showPreview(snapshot);}catch(error){message(error.message);throw error;}finally{password='';busy=false;}return true;}
 if(action==='web-erp-apply'){if(!preview)throw Error('请先读取或导入并预览');if(api.busy())throw Error('请等待云端同步完成');let result;api.commit('应用 ERP 库存与成本',()=>{result=applyErpSnapshot(api.state(),preview);});await api.flush();api.closeModal();api.render();api.toast(`ERP 数据已应用，匹配 ${result.matched} 个商品`);preview=null;return true;}return false;}
 return {open,actions};
}
