import {createRequire} from 'node:module';
import {readFile,writeFile,mkdir,copyFile,readdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {createHash} from 'node:crypto';
import './build.mjs';
const require=createRequire(new URL('../prototype/package.json',import.meta.url));
const {build}=require('esbuild');
const root=fileURLToPath(new URL('./',import.meta.url));
const version=JSON.parse(await readFile(path.join(root,'package.json'),'utf8')).version;
const out=path.join(root,'releases','web-workbench-'+version);
await mkdir(out,{recursive:true});
const raw=await readFile(path.join(root,'.env.local'),'utf8');
const original=JSON.parse(raw.split(/\r?\n/).find(l=>l.startsWith('CLOUDBASE_PUBLIC_CONFIG=')).slice('CLOUDBASE_PUBLIC_CONFIG='.length));
const config=Object.fromEntries(['envId','region','functionName','accessKey'].map(k=>[k,original[k]]));
if(Object.values(config).some(v=>typeof v!=='string'||!v))throw Error('缺少公开云端配置');
let html=await readFile(path.join(root,'dist/cloud.html'),'utf8');
html=html.replace('配置工作台 · 轻量网页版</title>',`配置工作台 · 网页版 ${version}</title>`).replace(/<a href="\.\/index\.html">[^<]*<\/a>/g,'');
for(const folder of ['static','local/dist'])await mkdir(path.join(out,folder),{recursive:true});
for(const folder of ['static','local/dist'])for(const name of ['index.html','cloud.html'])await writeFile(path.join(out,folder,name),html);
await build({entryPoints:[path.join(root,'server.mjs')],outfile:path.join(out,'local/server.mjs'),bundle:true,platform:'node',format:'esm',target:'node22',external:['mssql'],legalComments:'none'});
await writeFile(path.join(out,'local/.env.local'),'CLOUDBASE_PUBLIC_CONFIG='+JSON.stringify(config)+'\n');
await writeFile(path.join(out,'local/package.json'),JSON.stringify({name:'diy-workbench-local',version,private:true,type:'module',engines:{node:'>=22'},scripts:{start:'node server.mjs'},dependencies:{mssql:'12.7.2'}},null,2));
await writeFile(path.join(out,'local/start.cmd'),'@echo off\r\ncd /d "%~dp0"\r\nnode server.mjs\r\npause\r\n');
await writeFile(path.join(out,'local/start.sh'),'#!/bin/sh\ncd -- "$(dirname -- "$0")" || exit 1\nexec node server.mjs\n');
await copyFile(path.join(root,'RELEASE-GUIDE.md'),path.join(out,'使用说明.md'));
await copyFile(path.join(root,'../prototype/workbench-erp.user.js'),path.join(out,'workbench-erp.user.js'));
await writeFile(path.join(out,'release.json'),JSON.stringify({product:'配置工作台轻量网页版',version,builtAt:new Date().toISOString(),databaseWrites:false,cloudProtocol:2},null,2));
console.log('Release prepared: '+out);
