import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {ErpJobs,validateSnapshot,mergeErp,costRows,applyManualCosts} from '../erp-sync.js';
import {seed,catalog as base} from './fixtures/workspace.mjs';
const identity={clientId:'test-client',account:'测试账号',warehouse:'公司大库',depotId:'2'};
const sample={goodsId:'47538',name:'ERP 原商品名',stockAvailable:12,erp:1300};
const context={module:{exports:{}}};vm.runInNewContext(fs.readFileSync(new URL('../workbench-erp.user.js',import.meta.url),'utf8'),context);const collector=context.module.exports;

test('ERP 合并保留人工价、人工时间和显示文案，只更新库存成本',()=>{const state=structuredClone(seed);state.sourceCatalog=structuredClone(base);state.costSource=costRows(state.sourceCatalog);const cost=state.costSource.find(r=>r.goodsId==='47538');cost.tax=1450;cost.taxUpdatedAt='2026-09-01T00:00:00Z';const before=state.configs[0].parts[0].name;const merged=mergeErp(state,[sample],base,'2026-09-15T00:00:00Z');const p=merged.next.configs[0].parts[0];assert.equal(p.erp,1300);assert.equal(p.stockAvailable,12);assert.equal(p.name,before);assert.equal(p.tax,1400);const updated=merged.next.costSource.find(r=>r.goodsId==='47538');assert.equal(updated.tax,1450);assert.equal(updated.taxUpdatedAt,cost.taxUpdatedAt);assert.equal(state.configs[0].parts[0].erp,1400);});
test('空值成本保留旧价并明确未知，未匹配不清零，新商品不伪造核算价',()=>{const result=mergeErp(seed,[{...sample,erp:null,stockAvailable:null},{goodsId:'999900099',name:'ERP 新商品',erp:20,stockAvailable:0}],base,'2026-09-15');const row=result.next.sourceCatalog.find(r=>r.goodsId==='47538');assert.equal(row.erp,1400);assert.equal(row.erpUnknown,true);assert.equal(row.stockAvailable,null);assert.equal(result.next.sourceCatalog[0].erpMissing,true);const added=result.next.costSource.find(r=>r.goodsId==='999900099');assert.equal(added.tax,null);assert.equal(added.stockAvailable,0);});
test('不完整、空批次、重复 ID 或非法字段都不能提交',()=>{assert.throws(()=>validateSnapshot({complete:false,rows:[sample],total:1}));assert.throws(()=>validateSnapshot({complete:true,rows:[],total:0}));assert.throws(()=>validateSnapshot({complete:true,rows:[sample,sample],total:2}));assert.throws(()=>validateSnapshot({complete:true,rows:[{...sample,erp:undefined}],total:1}));assert.equal(validateSnapshot({complete:true,rows:[sample],total:1}).length,1);});
test('任务只允许认领页面提交，拒绝跨账号、过期与重复回传',()=>{const jobs=new ErpJobs(()=>null);jobs.start();const claim=jobs.poll(identity).job;const packet={...identity,jobId:claim.id,token:claim.token};assert.ok(jobs.verify(packet));assert.throws(()=>jobs.verify({...packet,clientId:'other'}));assert.throws(()=>jobs.verify({...packet,account:'另一账号'}));jobs.job.status='complete';assert.throws(()=>jobs.verify(packet));const pinned=new ErpJobs(()=> 'https://cqzs.3cerp.com|固定账号|2');assert.throws(()=>pinned.poll(identity));const timeout=new ErpJobs(()=>null);timeout.start();timeout.job.expiresAt=0;assert.equal(timeout.status().job.status,'failed');});
test('人工核算更新记录时间，ERP 和库存保持原值，已删除配置保留',()=>{const state=structuredClone(seed);state.sourceCatalog=structuredClone(base);state.costSource=costRows(state.sourceCatalog);state.configs[1].deletedAt='2026-09-15';const before=state.costSource.find(r=>r.goodsId==='47538').erp;const ids=applyManualCosts(state,[{goodsId:'47538',tax:1550}],'2026-09-15T01:00:00Z');assert.ok(ids.includes(state.configs[0].id));assert.equal(state.configs[0].parts[0].tax,1550);assert.equal(state.costSource.find(r=>r.goodsId==='47538').erp,before);assert.equal(state.sourceCatalog.find(r=>r.goodsId==='47538').taxUpdatedAt,'2026-09-15T01:00:00Z');assert.throws(()=>applyManualCosts(state,[{goodsId:'不存在',tax:1}]));});
test('复用采集分页校验，字段取自实际选择的成本列，null 库存不变零',async()=>{const raw={goods_id:47538,b_c_name:'配件',n_stock_able:null,verified_cost:'1300.50'};const rows=await collector.collectPages(async page=>({result:true,total:2,data:[{...raw,goods_id:47538+page}]}));assert.equal(rows.length,2);const normalized=collector.normalizeRows(rows,'verified_cost');assert.equal(normalized[0].erp,1300.5);assert.equal(normalized[0].stockAvailable,null);assert.throws(()=>collector.normalizeRows(rows,'missing_cost'));await assert.rejects(()=>collector.collectPages(async page=>({total:2,data:page?[]:[raw]})));});
