import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeSqlBundle,readSqlBundle,SQL_QUERIES} from '../sql-source.mjs';
import {sqlStockPlan,createSqlRoutes} from '../sql-sync.mjs';
import {projectWorkspace,applyWorkspace} from '../workspace-records.mjs';
const id='9007199254740993';
const catalog={goods_id:id,'商品名称':'CPU','商品编码':'sku-1','总数量':90,'可销数':80,'待入':0};
const warehouse={...catalog,'库房':'公司大库','分库数':8,'分库可销数':3,'分库待入':0,'库存成本':345};
const bundle={catalog:[catalog],warehouses:[warehouse]};
const state=()=>({revision:2,configs:[{id:'c',parts:[{goodsId:id,name:'自定名',erp:500,tax:510,stockAvailable:6}]}],sourceCatalog:[{goodsId:id,name:'自定名',erp:500,tax:510,stockAvailable:6}],costSource:[]});
test('company warehouse uses confirmed unit inventory cost, never another depot or total value',()=>{const rows=normalizeSqlBundle({catalog:[catalog],warehouses:[{...warehouse,'库房':'其他库','库存成本':9999,'分库成本':888},{...warehouse,'库存成本':12.34,'分库成本':999,'分库总金额':99999}]});assert.equal(rows[0].erp,12.34);assert.equal(normalizeSqlBundle({...bundle,warehouses:[]})[0].erp,null);assert.throws(()=>normalizeSqlBundle({...bundle,warehouses:[{...warehouse,'库存成本':undefined}]}),/无效/);assert.throws(()=>normalizeSqlBundle({...bundle,warehouses:[{...warehouse,'库存成本':-1}]}),/成本/);});
test('SQL routes save and autofill by stable member identity, opt-out clears local credentials',async()=>{
 let response,owner='session-1',member='team-A',current=state();const saved=new Map(),credentials={async save(key,value){saved.set(key,structuredClone(value));},async read(key){return saved.has(key)?{saved:true,...saved.get(key)}:{saved:false};},async clear(key){saved.delete(key);}};
 const routes=createSqlRoutes({json:(_r,_s,v)=>response=v,body:async r=>r.data,getState:()=>current,commit:async fn=>current=await fn(current),getIdentity:()=>owner,getMember:()=>member,credentials,reader:async()=>bundle});
 const call=(action,data,method='POST')=>routes({method,data},{},{pathname:'/api/sql-sync/'+action});
 await call('preview',{settings:{server:'host',database:'db',user:'reader'},password:'synthetic-password',remember:true});assert.equal(saved.get(member).password,'synthetic-password');assert.ok(!JSON.stringify(current).includes('synthetic-password'));
 owner='session-after-restart';await call('credentials',undefined,'GET');assert.equal(response.password,'synthetic-password');member='team-B';await call('credentials',undefined,'GET');assert.equal(response.saved,false);member='team-A';await call('preview',{settings:{server:'host',database:'db',user:'reader'},password:'synthetic-password',remember:false});assert.equal(saved.size,0);
 await call('forget',{});assert.equal(response.saved,false);
});
test('SQL uses company depot stock, exact string IDs and null for missing depot',()=>{assert.equal(normalizeSqlBundle(bundle)[0].stockAvailable,3);assert.equal(normalizeSqlBundle(bundle)[0].goodsId,id);assert.equal(normalizeSqlBundle({...bundle,warehouses:[]})[0].stockAvailable,null);assert.throws(()=>normalizeSqlBundle({...bundle,catalog:[{...catalog,goods_id:Number(id)}]}));assert.throws(()=>normalizeSqlBundle({...bundle,warehouses:[warehouse,warehouse]}));assert.throws(()=>normalizeSqlBundle({...bundle,catalog:[]}));assert.throws(()=>normalizeSqlBundle({...bundle,catalog:[catalog,{...catalog,goods_id:'2'}]}));});
test('SQL updates local ERP cost and stock, preserves names, manual prices and missing IDs',()=>{const before=state();before.configs.push({id:'deleted',deletedAt:'date',parts:[{goodsId:id,stockAvailable:100}]});before.sourceCatalog.push({goodsId:'2',stockAvailable:70});const plan=sqlStockPlan(before,normalizeSqlBundle(bundle));assert.equal(plan.next.configs[0].parts[0].stockAvailable,3);assert.equal(plan.next.configs[0].parts[0].erp,345);assert.equal(plan.next.configs[0].parts[0].tax,510);assert.equal(plan.next.configs[0].parts[0].name,'自定名');assert.equal(plan.next.configs[1].parts[0].stockAvailable,100);assert.equal(plan.next.sourceCatalog[1].stockAvailable,70);assert.equal(before.configs[0].parts[0].stockAvailable,6);});
test('driver runs fixed SELECTs only and closes connections without leaking secrets',async()=>{let closed=0,queries=[];class ConnectionPool{async connect(){}request(){return{query:async q=>{queries.push(q);return{recordset:q===SQL_QUERIES[0]?[warehouse]:[catalog]};}};}async close(){closed++;}}const config={server:'host',database:'db',user:'reader'};await readSqlBundle(config,'secret',{driver:{ConnectionPool}});assert.deepEqual(queries,SQL_QUERIES);assert.equal(closed,1);class Failed extends ConnectionPool{async connect(){throw Error('secret');}}await assert.rejects(()=>readSqlBundle(config,'secret',{driver:{ConnectionPool:Failed}}),e=>!e.message.includes('secret'));assert.equal(closed,2);});
test('preview is read-only and apply blocks stale state, changed owner and repeated use',async()=>{let current=state(),owner='a',response;const routes=createSqlRoutes({json:(_r,_s,value)=>response=value,body:async req=>req.data,getState:()=>current,commit:async fn=>{current=await fn(current);},getIdentity:()=>owner,reader:async()=>bundle});const call=async(action,data)=>routes({method:'POST',data},{},{pathname:'/api/sql-sync/'+action});const preview=async()=>{await call('preview',{settings:{server:'host',database:'db',user:'reader'},password:'secret'});return response.id;};let token=await preview();assert.equal(current.revision,2);owner='b';await assert.rejects(()=>call('apply',{id:token}));owner='a';current.revision++;await assert.rejects(()=>call('apply',{id:token}));token=await preview();await call('apply',{id:token});assert.equal(current.configs[0].parts[0].stockAvailable,3);assert.equal(current.revision,4);assert.ok(!JSON.stringify(current).includes('secret'));await assert.rejects(()=>call('apply',{id:token}));});
test('SQL inventory stays local when cloud data is applied with existing and new scopes',async()=>{
 for(const scope of [null,'https://erp|account|2']){
  let current=state(),response;current.sourceCatalog[0].sourceId='source-1';current.costSource=[{...current.sourceCatalog[0],erpUpdatedAt:'old-cost-date'}];
  if(scope)current.erpSync={scope,updatedAt:'old-sync-date',costField:'verified-cost'};
  const routes=createSqlRoutes({json:(_r,_s,value)=>response=value,body:async req=>req.data,getState:()=>current,commit:async fn=>{current=await fn(current);},getIdentity:()=> 'member',reader:async()=>bundle});
  await routes({method:'POST',data:{settings:{server:'host',database:'db',user:'reader'},password:'secret'}},{},{pathname:'/api/sql-sync/preview'});
  await routes({method:'POST',data:{id:response.id}},{},{pathname:'/api/sql-sync/apply'});
  const fresh=applyWorkspace(current,projectWorkspace(current));
  assert.equal(fresh.costSource[0].stockAvailable,3);assert.equal(fresh.configs[0].parts[0].stockAvailable,3);assert.equal(fresh.sourceCatalog[0].stockAvailable,3);assert.ok(fresh.costSource[0].erpUpdatedAt!=='old-cost-date');assert.equal(fresh.costSource[0].erp,345);assert.equal(fresh.costSource[0].tax,510);assert.equal(fresh.erpSync.sqlSync.stockField,'分库可销数');
  if(scope){assert.equal(fresh.erpSync.scope,scope);assert.ok(fresh.erpSync.updatedAt!=='old-sync-date');}else{assert.match(fresh.erpSync.scope,/^sql:/);assert.ok(fresh.erpSync.updatedAt);}
 }
});

 test('先接 SQL 后脚本身份独立绑定，已有浏览器身份仍严格核对',async()=>{const {browserErpScope,ErpJobs}=await import('../erp-sync.js');const info={scope:'sql:stable'},identity={clientId:'test',account:'ERP成员',warehouse:'公司大库',depotId:'1'},jobs=new ErpJobs(()=>browserErpScope(info));jobs.start();assert.ok(jobs.poll(identity).job);info.browserScope=jobs.job.scope;assert.throws(()=>jobs.identity({...identity,account:'其他账号'}),/不一致/);assert.equal(info.scope,'sql:stable');});

 test('SQL 错误分类保留可操作原因且不回显驱动中的凭据',async()=>{const {sqlFailure}=await import('../sql-source.mjs');const secret='DO_NOT_SHOW_PASSWORD';for(const [error,code] of [[{code:'ESOCKET',message:secret,originalError:{code:'DEPTH_ZERO_SELF_SIGNED_CERT'}},'SQL_CERTIFICATE'],[{code:'ELOGIN',message:secret},'SQL_LOGIN'],[{code:'EREQUEST',number:4060,message:secret},'SQL_DATABASE'],[{code:'EREQUEST',number:229,message:secret},'SQL_PERMISSION'],[{code:'ETIMEOUT',message:secret},'SQL_TIMEOUT']]){const result=sqlFailure(error,'connect');assert.equal(result.code,code);assert.ok(!result.message.includes(secret));}assert.equal(sqlFailure(Error(secret),'driver').code,'SQL_DRIVER');});
