import test from 'node:test';
import assert from 'node:assert/strict';
import {SyncStore} from '../local-store/sync-store.mjs';
import {projectWorkspace,applyWorkspace,changesBetween} from '../workspace-records.mjs';
import {validateWorkspaceRecord} from '../workspace-validation.mjs';
import {mergeEditingState,sameEditingState} from '../workspace-ui-merge.js';
const fixture=()=>({configs:[{id:'c',shopId:'intel',name:'配置',price:200,parts:[{slot:'CPU',goodsId:'123',qty:1,tax:15,erp:12},{slot:'空',goodsId:'',qty:0,tax:0,erp:0}]}],templates:[{id:'t',name:'模板'}],sourceCatalog:[{sourceId:'s',shopId:'intel',goodsId:'123',name:'CPU',tax:15,erp:12}],costSource:[{goodsId:'123',name:'CPU',tax:15,erp:12,stockAvailable:5}],shopSettings:{intel:{coupon:5}},caseGallery:[],erpSync:{scope:'test',total:1},revision:1});
test('unchanged local receipt skips rebase, but remote business edits still require merge',()=>{const a=fixture(),b=fixture();b.revision=99;b.logs=[{message:'saved'}];assert.equal(sameEditingState(a,b),true);b.configs[0].name='remote edit';assert.equal(sameEditingState(a,b),false);b.configs=a.configs;b.shopSettings.intel.coupon=10;assert.equal(sameEditingState(a,b),false);});
test('配置/共享成本投影往返保留金额、空槽位和稳定行 ID',()=>{const s=fixture(),records=projectWorkspace(s);records.forEach(r=>validateWorkspaceRecord(r.type,r.id,r.data));const result=applyWorkspace(s,records);assert.equal(result.configs[0].parts[1].tax,0);assert.equal(result.configs[0].price,200);assert.equal(result.configs[0].parts[0].tax,15);assert.deepEqual(projectWorkspace(result),records);});
test('人工成本变化仅提交共享人工价，不提交库存分块',()=>{const before=fixture(),after=fixture();after.costSource[0].tax=17;after.configs[0].parts[0].tax=17;after.sourceCatalog[0].tax=17;assert.deepEqual(changesBetween(before,after).map(r=>r.type),['component']);const store=new SyncStore(':memory:',{protocolVersion:2,validate:validateWorkspaceRecord});store.editMany(projectWorkspace(after));const batch=store.nextBatch();const types=batch.map(r=>r.payload.entityType);assert.ok(!types.includes('erp_snapshot')&&!types.includes('erp_chunk'));store.close();});
test('本地业务状态与草稿在一个 SQLite 事务内提交',()=>{const s=new SyncStore(':memory:',{protocolVersion:2,validate:validateWorkspaceRecord});assert.throws(()=>s.editMany(projectWorkspace(fixture()),()=>{throw Error('落盘失败');}));assert.equal(s.list().length,0);assert.equal(s.meta('workspaceState'),undefined);s.close();});
test('保存回执遇到继续输入，保留独立更新并检测同字段冲突',()=>{const base=fixture(),local=fixture(),remote=fixture();local.configs[0].name='正在输入';remote.configs[0].footer='他人备注';const result=mergeEditingState(base,local,remote);assert.equal(result.conflict,false);assert.equal(result.state.configs[0].name,'正在输入');assert.equal(result.state.configs[0].footer,'他人备注');remote.configs[0].name='别人名称';assert.equal(mergeEditingState(base,local,remote).conflict,true);});

test('正式备份恢复保留业务状态、启用状态和未确认提交',()=>{const options={protocolVersion:2,validate:validateWorkspaceRecord},s=new SyncStore(':memory:',options),r=new SyncStore(':memory:',options);s.bind('workbench','member');s.setMeta('enabled',true);s.editMany(projectWorkspace(fixture()),fixture());const batch=s.nextBatch();r.restore(s.backup());assert.equal(r.meta('enabled'),true);assert.deepEqual(r.meta('workspaceState'),fixture());assert.deepEqual(r.nextBatch(),batch);assert.throws(()=>new SyncStore(':memory:').restore(s.backup()),/协议/);s.close();r.close();});

test('撤销历史重基后仅撤销本人的字段，保留同步回执中的他人字段',()=>{const history=fixture(),saved=fixture(),remote=fixture();saved.configs[0].name='我的名称';remote.configs[0].name='我的名称';remote.configs[0].footer='他人备注';const result=mergeEditingState(saved,history,remote);assert.equal(result.conflict,false);assert.equal(result.state.configs[0].name,'配置');assert.equal(result.state.configs[0].footer,'他人备注');});
