import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawn,spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
import net from 'node:net';
const root=path.resolve('python-desktop'),{chromium}=createRequire(import.meta.url)(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const freePort=()=>new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});
await fs.mkdir(path.join(root,'.verification'),{recursive:true});
const directory=await fs.mkdtemp(path.join(root,'.verification/desktop-')),profile=path.join(directory,'profile'),data=path.join(directory,'data'),debugPort=await freePort();
const child=spawn(path.join(root,'.venv/Scripts/python.exe'),['-X','utf8',path.join(root,'tests/desktop_harness.py'),'--port','0'],{windowsHide:true,env:{...process.env,DIY_WORKBENCH_USER_DATA:profile,DIY_WORKBENCH_DATA_DIR:data,DIY_WORKBENCH_DEBUG_PORT:String(debugPort)},stdio:['ignore','pipe','pipe']});
let logs='';child.stdout.on('data',b=>logs+=b);child.stderr.on('data',b=>logs+=b);const exited=new Promise(resolve=>child.on('exit',code=>resolve(code)));let browser,page;const checks=[],errors=[];
const sdk=`let session=JSON.parse(localStorage.getItem('synthetic-sdk-session')||'null');export default {init(){return {auth:{onAuthStateChange(){},async signInWithPassword(v){if(v.password!=='synthetic')return{error:{message:'账号或密码错误'}};session={access_token:v.username,user:{is_anonymous:false}};localStorage.setItem('synthetic-sdk-session',JSON.stringify(session));return{data:{session}};},async getSession(){return{data:{session}}},async signOut(){session=null;localStorage.removeItem('synthetic-sdk-session');return{}}}}}};`;
try{
 for(let i=0;i<120;i++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/version`);if(response.ok)break;}catch{}if(child.exitCode!==null)throw Error('Desktop failed: '+logs);await new Promise(r=>setTimeout(r,250));}
 browser=await chromium.connectOverCDP(`http://127.0.0.1:${debugPort}`);const context=browser.contexts()[0];page=context.pages()[0]||await context.waitForEvent('page');await page.waitForURL(/^http:\/\/127\.0\.0\.1:/);page.on('pageerror',e=>errors.push(e.message));await page.route('**/vendor/cloudbase.js',r=>r.fulfill({contentType:'text/javascript',body:sdk}));await page.reload();await page.locator('#startup-login').waitFor();assert.equal(await page.locator('.workspace').isVisible(),false);assert.equal((await page.request.get(new URL('/api/state',page.url()).href)).status(),401);checks.push('Python 原生窗口显示原界面；未登录不可读取业务数据');
 const login=async uid=>{await page.waitForFunction(()=>typeof document.querySelector('#startup-login')?.onsubmit==='function');await page.locator('[name=username]').fill(uid);await page.locator('[name=password]').fill('synthetic');await page.locator('#startup-login button').click();await page.locator('#login-screen').waitFor({state:'hidden',timeout:15000});};await login('A');await page.waitForFunction(()=>document.querySelector('[data-config=name]')?.value==='配置1',{timeout:20000});checks.push('新电脑登录后由 Python 自动下载配置并显示');
 await page.locator('#operator-open').click();assert.equal(await page.locator('#cloud-notice').isVisible(),false);await page.locator('#dialog .close').click();checks.push('空错误区域隐藏');
 await page.locator('[data-find="0"]').click();await page.locator('#catalog-search').fill('ERP 原名');assert.equal(await page.locator('#catalog-results strong').first().textContent(),'输出源优化描述');await page.locator('[data-catalog="0"]').click();await page.evaluate(()=>window.workbenchBeforeQuit());checks.push('配件搜索优先显示输出源优化描述');
 await page.locator('#erp-sync').click();await page.locator('#sql-connection-form').waitFor();for(const [key,value]of Object.entries({server:'synthetic-host',database:'synthetic-db',user:'reader',password:'synthetic-password'}))await page.locator('#sql-'+key).fill(value);await page.locator('#sql-read').click();await page.locator('.sql-diff-table').waitFor();await page.locator('#sql-apply').click();await page.locator('#erp-last').filter({hasText:'SQL 库存'}).waitFor();const state=await(await page.request.get(new URL('/api/state',page.url()).href)).json();assert.equal(state.costSource[0].erp,99.25);assert.equal(state.costSource[0].stockAvailable,8);assert.equal(state.costSource[0].tax,120);checks.push('Python SQL 预览与确认应用更新本机单件成本和可销数，人工价保留');
 await page.locator('#erp-sync').click();await page.locator('#sql-message').filter({hasText:'已从本机'}).waitFor();assert.equal(await page.locator('#sql-password').inputValue(),'synthetic-password');await page.locator('#dialog .close').click();checks.push('Python DPAPI 保存后再次打开自动填入账号密码');
 await page.locator('[data-config=name]').fill('Python 桌面保存验证');await page.evaluate(()=>window.workbenchBeforeQuit());await page.reload();await page.waitForFunction(()=>document.querySelector('[data-config=name]')?.value==='Python 桌面保存验证');checks.push('编辑保存到 Python 本机存储，刷新和登录恢复后保持');
 await page.locator('#workspace-sync-status').filter({hasText:'已同步'}).waitFor({timeout:15000});const imgs=await fs.readdir(path.join(data,'images'));assert.ok(imgs.some(x=>x.endsWith('.png')));checks.push('原 Canvas 配置图仍能生成并由 Python 保存 PNG');
 await page.locator('#operator-open').click();await page.locator('#cloud-history').click();await page.locator('[data-version]').first().waitFor();await page.locator('[data-version]').first().click();await page.locator('#version-apply').waitFor();await page.locator('#dialog .close').click();checks.push('Python 历史版本列表和差异预览可用');
 await page.locator('#operator-open').click();await page.locator('#cloud-switch').click();await page.locator('#startup-login').waitFor();await login('B');assert.match(await page.locator('#operator-open').textContent(),/B/);await page.locator('#erp-sync').click();await page.waitForFunction(()=>document.querySelector('#sql-read')&&!document.querySelector('#sql-read').disabled);assert.equal(await page.locator('#sql-password').inputValue(),'');await page.locator('#dialog .close').click();checks.push('切换账号后保留配置，各成员 SQL 密码隔离');
 await fs.mkdir(path.join(root,'verification'),{recursive:true});await page.screenshot({path:path.join(root,'verification/python-desktop.png')});
 assert.deepEqual(errors,[]);await page.locator('[data-config=name]').fill('关闭窗口自动保存');const runtime=JSON.parse(await fs.readFile(path.join(profile,'desktop-runtime.json'),'utf8'));const close=spawnSync(path.join(root,'.venv/Scripts/python.exe'),[path.join(root,'tests/close-window.py'),String(runtime.pid)],{encoding:'utf8',windowsHide:true});assert.equal(close.status,0,close.stderr);await Promise.race([exited,new Promise((_,reject)=>setTimeout(()=>reject(Error('Desktop did not shut down')),15000))]);const saved=JSON.parse(await fs.readFile(path.join(data,'state.json'),'utf8'));assert.equal(saved.configs[0].name,'关闭窗口自动保存');checks.push('点击窗口关闭时 Python 窗口等待当前编辑保存后退出');
 await fs.writeFile(path.join(root,'verification/desktop.json'),JSON.stringify({at:new Date().toISOString(),checks,errors,syntheticCloud:true,syntheticSql:true,realCloudWrites:false},null,2));console.log(JSON.stringify({passed:checks.length,directory}));
}catch(error){console.error(JSON.stringify({message:error.message,checks,errors,logs}));if(page)console.error(await page.locator('body').innerText().catch(()=>''));throw error;}
finally{if(browser)await browser.close().catch(()=>{});if(child.exitCode===null)child.kill();}
