import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
const root=path.resolve('python-desktop');
const {chromium}=createRequire(import.meta.url)(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const directory=await fs.mkdtemp(path.join(root,'.verification/local-first-')),data=path.join(directory,'data');
const child=spawn(path.join(root,'.venv/Scripts/python.exe'),['-X','utf8',path.join(root,'tests/local_first_harness.py'),'--headless','--port','0'],{windowsHide:true,env:{...process.env,DIY_WORKBENCH_DATA_DIR:data,DIY_WORKBENCH_USER_DATA:path.join(directory,'profile')},stdio:['ignore','pipe','pipe']});
let logs='',browser;child.stderr.on('data',b=>logs+=b);
const sdk=`let session=null;export default {init(){return {auth:{onAuthStateChange(){},async signInWithPassword(v){session={access_token:v.username,user:{is_anonymous:false}};return{data:{session}};},async getSession(){return{data:{session}}},async signOut(){session=null;return{}}}}}};`;
const report={checks:[],directory};
try{
 const url=await new Promise((resolve,reject)=>{let output='';const timer=setTimeout(()=>reject(Error('Startup timeout '+logs)),20000);child.stdout.on('data',b=>{output+=b;const match=output.match(/WORKBENCH_READY (http:\/\/\S+)/);if(match){clearTimeout(timer);resolve(match[1]);}});child.once('exit',code=>reject(Error('Test backend exited '+code+' '+logs)));});
 browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://**',r=>r.abort());
 await page.route('**/vendor/cloudbase.js',r=>r.fulfill({contentType:'text/javascript',body:sdk}));
 await page.addInitScript(()=>{window.createdCanvases=0;const create=document.createElement.bind(document);document.createElement=(tag,...args)=>{if(tag==='canvas')window.createdCanvases++;return create(tag,...args);};});
 await page.goto(url);await page.waitForFunction(()=>typeof document.querySelector('#startup-login')?.onsubmit==='function');await page.locator('[name=username]').fill('A');await page.locator('[name=password]').fill('synthetic');await page.locator('#startup-login button').click();
 await page.waitForFunction(()=>document.querySelector('[data-config=name]')?.value==='配置1');await page.waitForFunction(()=>document.querySelector('#poster').height>500);
 const state=async()=>(await page.request.get(url+'/api/state')).json();
 const cloud=async()=>(await fs.readFile(path.join(data,'synthetic-cloud-calls.json'),'utf8'));
 const syncCalls=async()=>JSON.parse(await cloud()).filter(a=>a.startsWith('sync.'));
 const baseline=await syncCalls();assert.ok(baseline.includes('sync.pull'));
 const localSaved=()=>page.waitForFunction(()=>document.querySelector('#save-status').textContent.startsWith('已保存'));
 const original=(await state()).configs[0];
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=1200;c.height=600;const x=c.getContext('2d');x.fillStyle='#ff0000';x.fillRect(0,0,c.width,c.height);return c.toDataURL().split(',')[1];});
 await page.locator('#poster-image-file').setInputFiles({name:'本地拖动测试.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.locator('#poster-image-size').waitFor();await localSaved();
 await page.waitForFunction(()=>document.querySelector('#image-status').textContent.startsWith('图片已保存'));
 const before=(await state()).configs[0];const initial=await page.locator('#poster-selection').boundingBox();
 await page.evaluate(()=>window.createdCanvases=0);
 await page.mouse.move(initial.x+20,initial.y+20);await page.mouse.down();
 for(let i=1;i<=18;i++)await page.mouse.move(initial.x+20+i*3,initial.y+20+i*2);
 await page.waitForFunction(()=>Number(document.querySelector('#poster-image-x').value)>10);
 const during=await page.locator('#poster-selection').boundingBox();assert.ok(during.x>initial.x+25,'selection must follow before pointerup');
 const dragCanvases=await page.evaluate(()=>window.createdCanvases);assert.equal(dragCanvases,0,'drag must reuse cached layout/canvases');await page.mouse.up();await localSaved();
 const moved=(await state()).configs[0];assert.notDeepEqual(moved.posterImages[0].transforms,before.posterImages[0].transforms);assert.deepEqual(moved.parts,before.parts);
 report.checks.push('拖动释放前画面跟随；拖动期间不创建画布；价格配件不变');report.dragCanvases=dragCanvases;
 await page.locator('#undo').click();await localSaved();assert.deepEqual((await state()).configs[0].posterImages[0].transforms,before.posterImages[0].transforms);
 await page.locator('#redo').click();await localSaved();assert.deepEqual((await state()).configs[0].posterImages[0].transforms,moved.posterImages[0].transforms);report.checks.push('拖动撤销与重做恢复正确位置');
 // Cached composition must match the full-quality export, including transparency/layer order.
 report.render=await page.evaluate(async c=>{const {renderPoster}=await import('/poster.js');c=structuredClone(c);const fast=await renderPoster(c,700,{interactive:true}),layout=JSON.stringify(fast.textRegions);const t=performance.now();for(let i=0;i<60;i++){c.posterImages[0].transforms.long={x:70+i,y:180,width:180};fast.redrawImages(c);}const fastMs=performance.now()-t;const t2=performance.now();const full=await renderPoster(c,700);const fullMs=performance.now()-t2;const a=fast.canvas.getContext('2d').getImageData(0,0,fast.canvas.width,fast.canvas.height).data,b=full.canvas.getContext('2d').getImageData(0,0,full.canvas.width,full.canvas.height).data;return{pixelsEqual:a.every((v,i)=>v===b[i]),layoutUnchanged:layout===JSON.stringify(fast.textRegions),fast60Ms:fastMs,fullMs};},moved);
 assert.equal(report.render.pixelsEqual,true);assert.equal(report.render.layoutUnchanged,true);
 // Create gallery metadata for the local fixture through the normal local save API.
 let current=await state();current.caseGallery=[{id:'local-gallery',url:moved.posterImages[0].url,name:'图库测试',brand:'测试',model:'测试',color:'红色',edition:'通用'}];
 const saved=await page.request.post(url+'/api/state',{data:{...current,baseRevision:current.revision}});assert.ok(saved.ok());
 await page.reload();await page.waitForFunction(()=>typeof document.querySelector('#startup-login')?.onsubmit==='function');await page.locator('[name=username]').fill('A');await page.locator('[name=password]').fill('synthetic');await page.locator('#startup-login button').click();await page.waitForFunction(()=>document.querySelector('[data-config=name]')?.value==='配置1');
 await page.locator('#poster-add-image').click();await page.locator('#poster-image-gallery').click();
 const block=[];await page.route('**/api/image',route=>new Promise(resolve=>block.push(()=>route.continue().then(resolve))));
 await page.locator('[data-gallery-use="local-gallery"]').click();await page.locator('#dialog').waitFor({state:'hidden',timeout:1500});await localSaved();assert.equal((await state()).configs[0].posterImages.length,2);report.checks.push('图库选图先返回编辑；本地保存不等待 PNG');
 await page.unroute('**/api/image');for(const release of block)await release();
 await page.locator('#asset-button').click();await page.locator('[data-gallery-use="local-gallery"]').click();await page.locator('#dialog').waitFor({state:'hidden',timeout:1500});await localSaved();assert.equal((await state()).configs[0].caseImage,moved.posterImages[0].url);report.checks.push('图库替换机箱图不等待 PNG 保存');
 assert.deepEqual(await syncCalls(),baseline,'local edits, image use and relogin must not trigger cloud sync');report.checks.push('本地编辑、图片操作、重新登录均未触发云同步');
 await page.locator('#workspace-sync').click();await page.locator('#cloud-pause').click();await page.waitForFunction(()=>document.querySelector('#cloud-pause')?.textContent.includes('恢复'));assert.match(await page.locator('#cloud-pause').textContent(),/恢复/);await page.locator('#cloud-now').click();
 await page.waitForFunction(()=>document.querySelector('#workspace-sync-status').textContent==='已暂停');
 const deadline=Date.now()+10000;while((await syncCalls()).length===baseline.length&&Date.now()<deadline)await new Promise(r=>setTimeout(r,100));assert.ok((await syncCalls()).includes('sync.pushBatch'));report.checks.push('暂停自动同步时立即同步仍上传待提交修改');
 await page.locator('#dialog .close').click();
 const download=page.waitForEvent('download');await page.locator('#download').click();const file=await(await download).path();assert.equal((await fs.readFile(file)).subarray(0,8).toString('hex'),'89504e470d0a1a0a');report.checks.push('正式 PNG 导出正常');
 await page.screenshot({path:path.join(root,'verification/local-first.png')});assert.deepEqual(errors,[]);report.ok=true;report.errors=errors;
 await fs.writeFile(path.join(root,'verification/local-first.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{if(browser)await browser.close();child.kill();await new Promise(r=>child.exitCode!==null?r():child.once('exit',r));}
