import fs from 'node:fs/promises';import path from 'node:path';import net from 'node:net';import assert from 'node:assert/strict';import {spawn,spawnSync} from 'node:child_process';import {createRequire} from 'node:module';
const root=path.resolve('python-desktop'),{chromium}=createRequire(import.meta.url)(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
await fs.mkdir(path.join(root,'.verification'),{recursive:true});const build=JSON.parse(await fs.readFile(path.join(root,'verification/latest-build.json'),'utf8'));const dir=await fs.mkdtemp(path.join(root,'.verification/packaged-')),app=path.join(dir,'app'),profile=path.join(app,'data/runtime');await fs.cp(build.directory,app,{recursive:true});const legacy=path.join(dir,'roaming/DIYWorkbench');await fs.mkdir(path.join(legacy,'data'),{recursive:true});await fs.copyFile(path.join(root,'tests/fixtures/state.json'),path.join(legacy,'data/state.json'));await fs.writeFile(path.join(legacy,'desktop-runtime.json'),JSON.stringify({port:0}));
const port=await new Promise(r=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>r(p));});});
const exe=path.join(app,path.basename(build.executable));
const env={...process.env,PATH:path.join(process.env.SystemRoot,'System32'),DIY_WORKBENCH_PORT:'0',APPDATA:path.join(dir,'roaming'),DIY_WORKBENCH_DEBUG_PORT:String(port)};delete env.PYTHONHOME;delete env.PYTHONPATH;delete env.DIY_WORKBENCH_USER_DATA;delete env.DIY_WORKBENCH_DATA_DIR;
const child=spawn(exe,[],{windowsHide:false,env,stdio:'ignore'}),exited=new Promise(r=>child.on('exit',r));let browser,page;
try{
 for(let i=0;i<160;i++){try{if((await fetch(`http://127.0.0.1:${port}/json/version`)).ok)break;}catch{}if(child.exitCode!==null)throw Error('Packaged app exited '+child.exitCode);await new Promise(r=>setTimeout(r,250));}
 browser=await chromium.connectOverCDP(`http://127.0.0.1:${port}`);page=browser.contexts()[0].pages()[0];await page.waitForURL(/^http:\/\/127\.0\.0\.1:/);await page.locator('#startup-login').waitFor();assert.equal(await page.locator('.workspace').isVisible(),false);assert.equal((await page.request.get(new URL('/api/state',page.url()).href)).status(),401);
 const runtime=JSON.parse(await fs.readFile(path.join(profile,'desktop-runtime.json'),'utf8'));assert.equal(runtime.backend,'python');assert.equal(runtime.version,build.version);const migrated=JSON.parse(await fs.readFile(path.join(app,'data/state.json'),'utf8'));assert.equal(migrated.configs.length,3);assert.equal(JSON.parse(await fs.readFile(path.join(legacy,'data/state.json'),'utf8')).configs.length,3);assert.ok(await fs.stat(path.join(app,'data/portable-migration.json')));await page.waitForFunction(()=>typeof window.pywebview?.api?.close_ready==='function');const close=spawnSync(path.join(root,'.venv/Scripts/python.exe'),[path.join(root,'tests/close-window.py'),String(runtime.pid)],{windowsHide:true,encoding:'utf8'});assert.equal(close.status,0,close.stderr);assert.equal(await Promise.race([exited,new Promise((_,reject)=>setTimeout(()=>reject(Error('Close timeout')),15000))]),0);
 const internal=path.join(build.directory,'_internal');const seed=JSON.parse(await fs.readFile(path.join(internal,'web/seed.json'),'utf8'));for(const key of ['configs','templates','sourceCatalog','costSource','caseGallery','logs'])assert.deepEqual(seed[key],[]);
 const sourceFiles=(await fs.readdir(path.resolve('prototype'),{withFileTypes:true})).filter(e=>e.isFile()&&/\.(js|html|css)$/.test(e.name));for(const e of sourceFiles)assert.deepEqual(await fs.readFile(path.join(internal,'web',e.name)),await fs.readFile(path.resolve('prototype',e.name)),e.name);
 const walk=async directory=>(await Promise.all((await fs.readdir(directory,{withFileTypes:true})).map(async e=>e.isDirectory()?walk(path.join(directory,e.name)):[path.join(directory,e.name)]))).flat();const files=await walk(build.directory);assert.equal(files.filter(f=>/\.sqlite(?:$|-)|[\\/]sql-credentials[\\/]|[\\/]state\.json$|[\\/](?:node|electron)\.exe$/i.test(f)).length,0);
 const config=(await fs.readFile(path.join(internal,'web/.env.local'),'utf8')).split(/\r?\n/).filter(Boolean);assert.ok(config.every(l=>l.startsWith('CLOUDBASE_PUBLIC_CONFIG=')));const parsed=JSON.parse(config[0].split('=').slice(1).join('='));assert.deepEqual(Object.keys(parsed).sort(),['accessKey','envId','functionName','region'].sort());
 const report={at:new Date().toISOString(),version:build.version,portableDataBesideExe:true,legacyDataImported:true,originalDataPreserved:true,noPythonOrNodeOnPath:true,backend:'python',loginGate:true,gracefulShutdown:true,uiSourceFilesIdentical:sourceFiles.length,emptySeed:true,businessDataIncluded:false,credentialFilesIncluded:false,nodeOrElectronRuntimeIncluded:false};await fs.writeFile(path.join(root,'verification/packaged-'+build.version+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{if(browser)await browser.close().catch(()=>{});if(child.exitCode===null)child.kill();}
