import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
import net from 'node:net';
const root=path.resolve('python-desktop');
const {chromium}=createRequire(import.meta.url)(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const freePort=()=>new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});
await fs.mkdir(path.join(root,'.verification'),{recursive:true});
const directory=await fs.mkdtemp(path.join(root,'.verification/template-area-ui-'));
const port=await freePort();
const child=spawn(path.join(root,'.venv/Scripts/python.exe'),['-X','utf8',path.join(root,'tests/desktop_harness.py')],{windowsHide:true,env:{...process.env,DIY_WORKBENCH_PORT:'0',DIY_WORKBENCH_USER_DATA:path.join(directory,'profile'),DIY_WORKBENCH_DATA_DIR:path.join(directory,'data'),DIY_WORKBENCH_DEBUG_PORT:String(port)},stdio:['ignore','pipe','pipe']});
let logs='';child.stdout.on('data',b=>logs+=b);child.stderr.on('data',b=>logs+=b);
let browser,page;
const sdk=`let session=JSON.parse(localStorage.getItem('synthetic-sdk-session')||'null');export default {init(){return {auth:{onAuthStateChange(){},async signInWithPassword(v){session={access_token:v.username,user:{is_anonymous:false}};localStorage.setItem('synthetic-sdk-session',JSON.stringify(session));return{data:{session}};},async getSession(){return{data:{session}}},async signOut(){session=null;return{}}}}}};`;
try{
 for(let i=0;i<120;i++){try{if((await fetch(`http://127.0.0.1:${port}/json/version`)).ok)break;}catch{}if(child.exitCode!==null)throw Error('Desktop failed: '+logs);await new Promise(r=>setTimeout(r,250));}
 browser=await chromium.connectOverCDP(`http://127.0.0.1:${port}`);const context=browser.contexts()[0];page=context.pages()[0]||await context.waitForEvent('page');await page.waitForURL(/^http:\/\/127\.0\.0\.1:/);
 await page.route('**/vendor/cloudbase.js',r=>r.fulfill({contentType:'text/javascript',body:sdk}));await page.reload();
 await page.waitForFunction(()=>typeof document.querySelector('#startup-login')?.onsubmit==='function');await page.locator('[name=username]').fill('A');await page.locator('[name=password]').fill('synthetic');await page.locator('#startup-login button').click();await page.locator('#login-screen').waitFor({state:'hidden',timeout:15000});
 await page.waitForFunction(()=>document.querySelector('[data-config=name]')?.value==='配置1',{timeout:20000});
 const state=()=>page.evaluate(()=>fetch('/api/state').then(r=>r.json()));
 const fixtureIds=await page.evaluate(async()=>{
  const before=await fetch('/api/state').then(r=>r.json()),next=structuredClone(before);
  Object.assign(next.configs[1],{productCategory:'主机模板',productId:'legacy-template',product:'独立主机模板',name:'模板原配置'});
  Object.assign(next.configs[2],{shopId:'gigabyte',productCategory:'主机模板',productId:'other-template',product:'他店主机模板',name:'他店模板配置'});
  const item=structuredClone(next.configs[0]);item.id='library-config';item.caseTransforms={long:{x:17,y:21,scale:1.3}};item.parts[0].sourceId='optimized';item.parts=[item.parts[0]];item.parts.push({slot:'内存',name:'DDR5 16GB',goodsId:'ram32',qty:2,tax:100,erp:90},{slot:'硬盘',name:'NVMe SSD 1TB',goodsId:'ssd1',qty:1,tax:300,erp:290},{slot:'显卡',name:'无卡',goodsId:'0',qty:1,specialComponent:true,tax:0,erp:0});item.actualParts=structuredClone(item.parts);next.sourceCatalog.push({sourceId:'template-cpu',shopId:'intel',goodsId:'47538',name:'英特尔 酷睿 i5 14600KF 14核20线程',tax:1200,erp:1180,addonText:'处理器升级说明'});
  next.templates=[{id:'lib-intel',shopId:'intel',name:'已保存模板',configs:[item]},{id:'lib-other',shopId:'gigabyte',name:'他店模板库',configs:[{...structuredClone(item),id:'other-lib-config',shopId:'gigabyte'}]}];
  const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...next,baseState:before,baseRevision:before.revision,message:'synthetic template fixture'})});if(!r.ok)throw Error(await r.text());
  return {normal:next.configs[0].id,legacy:next.configs[1].id,other:next.configs[2].id};
 });
 await page.reload();await page.locator('#template-section-toggle').waitFor();
 assert.equal(await page.locator('#config-list .config-item').count(),1);
 assert.equal(await page.locator(`[data-template-config-id="${fixtureIds.legacy}"]`).count(),0);
 await page.locator('#select-all').check();assert.match(await page.locator('#selected-count').textContent(),/1 套/);
 await page.locator('#template-section-toggle').click();
 const legacyGroup=page.locator('[data-template-product-toggle="legacy-template"]');
 if(await legacyGroup.getAttribute('aria-expanded')==='false')await legacyGroup.click();
 await page.locator(`[data-template-config-id="${fixtureIds.legacy}"]`).first().waitFor();
 assert.equal(await page.locator('[data-template-library-edit="lib-other"]').count(),0);
 await page.locator(`[data-template-config-id="${fixtureIds.legacy}"]`).first().click();
 await page.locator('[data-config=name]').fill('主机模板已编辑');
 await page.locator('#save').click();await page.waitForFunction(id=>fetch('/api/state').then(r=>r.json()).then(s=>s.configs.find(c=>c.id===id)?.name==='主机模板已编辑'),fixtureIds.legacy);
 assert.equal(await page.locator('[data-template-library-edit]').count(),0);
 assert.equal(await page.getByText('已保存的模板库',{exact:true}).count(),0);
 // Ordinary selections must survive the template-only delete action.
 await page.locator(`[data-template-config-id="${fixtureIds.legacy}"] input`).check();
 await page.locator('#template-delete-selected').click();
 await page.locator('#save').click();
 await page.waitForFunction(id=>fetch('/api/state').then(r=>r.json()).then(s=>!!s.configs.find(c=>c.id===id)?.deletedAt),fixtureIds.legacy);
 let saved=await state();
 assert.ok(!saved.configs.find(c=>c.id===fixtureIds.normal).deletedAt);
 assert.ok(!saved.configs.find(c=>c.id===fixtureIds.other).deletedAt);
 assert.equal(saved.templates.find(t=>t.id==='lib-intel').name,'已保存模板');
 await page.locator('.list-actions-menu > summary').click();
 await page.locator('#deleted-configs').click();
 await page.locator(`[data-restore-config="${fixtureIds.legacy}"]`).click();
 await page.locator('#dialog .close').click();
 await page.locator(`[data-id="${fixtureIds.normal}"]`).click();
 await page.locator('#template-section-toggle').click();
 await page.locator('#edit-product').click();
 await page.locator('#product-category').fill('主机模板');
 await page.locator('#product-apply').click();
 assert.equal(await page.locator('#template-section-toggle').getAttribute('aria-expanded'),'true');
 assert.equal(await page.locator(`[data-id="${fixtureIds.normal}"]`).count(),0);
 await page.locator(`[data-template-config-id="${fixtureIds.normal}"]`).waitFor();
 await page.locator('#template-library-add').click();
 assert.equal(await page.locator('#product-category').inputValue(),'主机模板');
 await page.locator('#product-name').fill('直接新建模板');
 await page.locator('#product-apply').click();
 await page.locator('[data-config=name]').fill('新增模板配置');
 await page.locator('#save').click();
 await page.waitForFunction(()=>fetch('/api/state').then(r=>r.json()).then(s=>s.configs.some(c=>c.product==='直接新建模板'&&c.name==='新增模板配置')));
 const after=await state(),created=after.configs.find(c=>c.product==='直接新建模板');
 assert.equal(created.productCategory,'主机模板');assert.equal(created.shopId,'intel');
 assert.equal(after.templates.length,2,'Existing saved library data is preserved');
 assert.ok(!after.configs.find(c=>c.id===fixtureIds.legacy).deletedAt);
 await page.screenshot({path:path.join(directory,'template-area.png')});
 await page.reload();await page.locator('#template-section-toggle').click();
 const createdGroup=page.locator(`[data-template-product-toggle="${created.productId}"]`);
 if(await createdGroup.getAttribute('aria-expanded')==='false')await createdGroup.click();
 await page.locator(`[data-template-config-id="${created.id}"]`).waitFor();
 // Saving an existing group must create an immediately editable sidebar group.
 await page.locator(`[data-template-config-id="${created.id}"]`).click();
 await page.locator('#product-panel .action-menu > summary').click();
 await page.locator('#save-product-template').click();
 await page.locator('#template-name').fill('保存后能找到');
 await page.locator('#template-save').click();
 await page.locator('#template-name').waitFor({state:'hidden'});
 const savedGroup=page.locator('[data-template-product-toggle]').filter({hasText:'保存后能找到'});
 await savedGroup.waitFor();
 const savedId=await savedGroup.getAttribute('data-template-product-toggle');
 const savedRow=page.locator(`[data-template-product-toggle="${savedId}"]`).locator('..').locator('[data-template-config-id]').first();
 await savedRow.click();await page.locator('[data-config=name]').fill('保存模板正常编辑');await page.locator('#save').click();
 await page.locator('#add-template').click();
 const card=page.locator('.template-card').filter({hasText:'保存后能找到'});
 assert.equal(await card.count(),1);
 await card.locator('[data-template-fold]').click();await card.locator('.template-choice').check();
 await page.locator('#template-use').click();await page.locator('#dialog').waitFor({state:'hidden'});
 await page.locator('#add-template').click();
 await page.locator(`[data-template-delete="${savedId}"]`).click();
 assert.equal(await page.locator(`[data-template-product-toggle="${savedId}"]`).count(),0);
 await page.locator('.template-deleted > summary').click();
 await page.locator(`[data-template-restore="${savedId}"]`).click();
 await page.locator('#dialog .close').click();await page.locator('#save').click();
 const finalState=await state();
 assert.equal(finalState.configs.filter(c=>c.productId===savedId&&!c.deletedAt).length,2);
 const imported=finalState.configs.find(c=>c.productId===savedId&&c.keepCorePartPlaceholders);
 assert.ok(imported);assert.deepEqual(imported.parts.slice(0,8).map(p=>p.slot),['CPU','散热','主板','内存','硬盘','显卡','电源','机箱']);
 const rendered=await page.evaluate(async c=>{const {renderPoster}=await import('/poster.js');const r=await renderPoster({...c,layout:'long'},1000);return {labels:r.textRegions.filter(t=>/^part\..*\.label$/.test(t.key)).map(t=>t.value),caseValue:r.textRegions.find(t=>t.key==='part.机箱.name')?.value,image:r.canvas.toDataURL('image/png')};},imported);
 assert.deepEqual(rendered.labels,['CPU','散热','主板','内存','硬盘','显卡','电源','机箱']);assert.equal(rendered.caseValue,'');
 await fs.writeFile(path.join(directory,'template-empty-placeholders.png'),Buffer.from(rendered.image.split(',')[1],'base64'));

 await page.reload();await page.locator('#template-section-toggle').click();
 await page.locator('[data-template-product-toggle]').filter({hasText:'保存后能找到'}).waitFor();
 await page.locator('[data-template-product-toggle]').filter({hasText:'已保存模板'}).waitFor();
 const beforeGroupDelete=await state();
 const groupIds=beforeGroupDelete.configs.filter(c=>c.productId===savedId&&!c.deletedAt).map(c=>c.id);
 assert.equal(groupIds.length,2);
 const groupToggle=page.locator(`[data-template-product-toggle="${savedId}"]`);
 if(await groupToggle.getAttribute('aria-expanded')==='true')await groupToggle.click();
 await page.locator(`[data-template-group-delete="${savedId}"]`).click();
 assert.equal(await page.locator(`[data-template-product-toggle="${savedId}"]`).count(),0);
 await page.locator('#save').click();
 await page.waitForFunction(ids=>fetch('/api/state').then(r=>r.json()).then(s=>ids.every(id=>s.configs.find(c=>c.id===id)?.deletedAt)),groupIds);
 const groupDeleted=await state();
 for(const c of beforeGroupDelete.configs.filter(c=>!groupIds.includes(c.id)))assert.equal(groupDeleted.configs.find(row=>row.id===c.id)?.deletedAt,c.deletedAt,'Other groups remain unchanged');
 await page.locator('#undo').click();await page.locator('#save').click();
 await page.locator(`[data-template-product-toggle="${savedId}"]`).waitFor();
 await page.screenshot({path:path.join(directory,'template-group-delete.png')});
 await page.locator('#shop-picker').selectOption('gigabyte');
 await page.locator('#template-section-toggle').click();
 assert.equal(await page.locator(`[data-template-config-id="${created.id}"]`).count(),0);
 assert.equal(await page.locator('[data-template-product-toggle="other-template"]').count(),1);
 const report={passed:true,directory,realWindow:true,isolatedData:true,normalEditorSaved:true,templateOnlySoftDelete:true,restoreVerified:true,categoryAutoMoved:true,newTemplateUsesNormalEditor:true,libraryDisplayRemoved:true,libraryDataPreserved:true,shopIsolation:true,reloadPreserved:true,savedTemplateInSidebar:true,savedTemplateEditable:true,pickerDeleteRestore:true,editedTemplateReusable:true,previousLibraryVisible:true,collapsedWholeGroupDelete:true,otherGroupsPreserved:true,wholeGroupUndo:true,templateEightSlotPlaceholders:true,blankRowsRendered:true};
 await fs.writeFile(path.join(directory,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{if(browser)await browser.close().catch(()=>{});if(child.exitCode===null)child.kill();}
