import {mountAddonChoices} from './addon-choices-ui.js';
import {selectableComponents} from './component-policy.js';
import {mountProductSearch} from './product-search.js';
import {addonItems,addonCheck,validateAddon,addonGroups,addonBatchPlan,addonSummary,addonKey,sourceAddonOptions,choiceDescription,addonChecks} from './addon-data.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v==null?'待补充':'¥'+(v/100).toFixed(2);
export function addonStatusHtml(a,costs,originals=[]){if(a.choices!==undefined)return addonChecks(a).map((v,i)=>`<section class="addon-choice-result"><strong>加购商品 ${i+1} · ${esc(v.text)}</strong>${addonStatusHtml(v,costs,originals)}</section>`).join('')||'<p class="hint">尚未选择加购商品</p>';if(!addonItems(a).length)return '<p class="hint">仅文字说明 · 不核算商品成本与差价</p>';const r=addonCheck(a,costs,originals),quoted=/^[+＋]\s*(\d+(?:\.\d{1,2})?)\s*元/.exec(a.text||''),mismatch=(a.qty??1)===1&&a.priceCents!=null&&quoted&&Math.round(Number(quoted[1])*100)!==a.priceCents;return `<div class="addon-check"><span>${esc(r.name||r.reason)}${a.goodsId?' · ID '+esc(a.goodsId):''}</span>${[...r.fields].sort((a,b)=>Number(b.key==='tax')-Number(a.key==='tax')).map(f=>`<span class="addon-${f.severity}">${f.label}：原配件 ${money(f.originalPriceCents)} ＋ 加购价 ${money(a.priceCents)} − 新配件成本 ${money(f.costCents)} ＝ 差价 ${money(f.diffCents)}</span>`).join('')}${r.needsAdjustment?'<strong class="addon-adjustment">ERP 与核算差价均达到红色阈值，需要重新调整加购描述。</strong>':''}${r.reason?`<small>${esc(r.reason)}</small>`:''}${mismatch?'<small>描述中的金额与设置的加购价不同，请一并核对描述。</small>':''}</div>`;}
export function mountAddonFields(root,{initial,getCosts,onChange=()=>{},owners,getOriginals=()=>owners||[],renderStatus}){
 const a={text:'',note:'',priceCents:null,...structuredClone(initial)},$=s=>root.querySelector(s);
 if(a.choices!==undefined){root.innerHTML='<div data-multi-products></div><label class="field">加购说明<input data-choice-note></label>';$('[data-choice-note]').value=a.note||'';const editor=mountAddonChoices($('[data-multi-products]'),{initial:a.choices,getCosts,sourceId:a.sourceId,onChange,renderCheck:v=>addonStatusHtml(v,getCosts(),getOriginals())});$('[data-choice-note]').oninput=onChange;return {read:(required=true)=>{const choices=editor.read(required);return {...a,choices,text:choiceDescription(choices),note:$('[data-choice-note]').value.trim()};},refresh:editor.refresh};}

 let lines=structuredClone(addonItems(a)),ownerPicker;
 root.innerHTML=`<p class="hint">商品可不选；添加多个商品时按各自数量合计成本，整组只使用下方一条描述。</p><div data-addon-items></div><button type="button" data-addon-item-add>＋ 添加核算商品</button><label class="field">加购价（整组总价）<input data-addon-price type="number" min="0" step=".01" value="${a.priceCents==null?'':(a.priceCents/100).toFixed(2)}"></label><label class="field">加购描述<textarea data-addon-text rows="2">${esc(a.text)}</textarea></label><label class="field">加购说明<input data-addon-note value="${esc(a.note)}"></label>${owners?'<div data-addon-owner-search></div><label class="field">原配件替换数量（仅关联原配件时使用）<input data-addon-original-qty type="number" min="1" max="100000" value="'+esc(a.originalQty??1)+'"></label>':''}<p class="hint">独立加购：加购总价 − 各商品成本×数量之和。关联原配件时，再加上被替换的原配件价格。优先看核算价，两项同时红色才提醒调整描述；不自动修改整机成本。</p><div data-addon-check></div>`;
 function read(required=true){const raw=$('[data-addon-price]').value;if(raw!==''&&!/^\d+(\.\d{1,2})?$/.test(raw))throw Error('加购价最多两位小数');const value={...a,text:$('[data-addon-text]').value.trim(),note:$('[data-addon-note]').value.trim(),items:structuredClone(lines),goodsId:lines.length===1?lines[0].goodsId:'',qty:lines.length===1?lines[0].qty:1,originalQty:owners?Number($('[data-addon-original-qty]').value):a.originalQty??1,priceCents:raw===''?null:Math.round(Number(raw)*100)};if(owners){if(ownerPicker.value())value.sourceId=ownerPicker.value();else delete value.sourceId;}return validateAddon(value,{required,costs:getCosts()});}
 function update(){try{$('[data-addon-check]').innerHTML=renderStatus?renderStatus(read(false)):addonStatusHtml(read(false),getCosts(),getOriginals());}catch(e){$('[data-addon-check]').textContent=e.message;}onChange();}
 function draw(){const host=$('[data-addon-items]');host.innerHTML=lines.map((line,i)=>`<section class="addon-card" data-addon-item="${i}"><div data-addon-product-search></div><label class="field">商品数量<input data-addon-qty type="number" min="1" max="100000" step="1" value="${esc(line.qty)}"></label><button type="button" data-addon-item-remove>移除此商品</button></section>`).join('');for(const [i,line] of lines.entries()){const node=host.children[i];mountProductSearch(node.querySelector('[data-addon-product-search]'),{getRows:()=>selectableComponents(getCosts()),getCosts,selected:line.goodsId,label:'核算商品 '+(i+1),onChange:row=>{line.goodsId=row?.goodsId||'';update();}});node.querySelector('[data-addon-qty]').oninput=e=>{line.qty=Number(e.target.value);update();};node.querySelector('[data-addon-item-remove]').onclick=()=>{lines.splice(i,1);draw();update();};}}
 if(owners)ownerPicker=mountProductSearch($('[data-addon-owner-search]'),{getRows:()=>owners,idKey:'sourceId',selected:a.sourceId,label:'关联原配件（可选）',placeholder:'输入配件名称或 ERP ID',describe:r=>r.slot+' · ID '+r.goodsId,emptySelection:'独立加购，不随配置配件替换',onChange:update});
 $('[data-addon-item-add]').onclick=()=>{lines.push({goodsId:'',qty:1});draw();update();};
 for(const e of root.querySelectorAll('[data-addon-price],[data-addon-text],[data-addon-note],[data-addon-original-qty]'))e.addEventListener('input',update);
 draw();update();return {read,refresh:update};
}
export function mountAddonVariants(root,{initial=[],sourceId,getCosts,getOriginals,onChange=()=>{}}){
 let drafts=structuredClone(initial),fields=[];
 function draw(){root.innerHTML=`<p class="hint">每个方案独立设置商品、数量、加购价和描述。勾选“展示此方案”可让多个方案一起显示；它们是可选升级，不会相加计入整机成本。</p><div data-variant-list></div><button type="button" data-variant-add>＋ 添加加购方案</button>`;const list=root.querySelector('[data-variant-list]');fields=drafts.map((a,i)=>{const node=document.createElement('section');node.className='addon-card';node.innerHTML=`<h5>加购方案 ${i+2}</h5><label><input type="checkbox" data-variant-show ${a.showTogether===true?'checked':''}> 展示此方案（可多选）</label><div data-variant-fields></div><button type="button" data-variant-remove>移除此方案</button>`;list.append(node);const field=mountAddonFields(node.querySelector('[data-variant-fields]'),{initial:{...a,sourceId},getCosts,getOriginals,onChange});const baseline=JSON.stringify(field.read(false)),read=field.read;field.read=(required=true)=>{const value=read(required),checked=node.querySelector('[data-variant-show]').checked;if(checked||a.showTogether!==undefined||checked!==(a.showTogether===true))value.showTogether=checked;if(JSON.stringify(value)===baseline)return structuredClone(a);if(a.sourceId===undefined)delete value.sourceId;return value;};node.querySelector('[data-variant-show]').onchange=onChange;node.querySelector('[data-variant-remove]').onclick=()=>{try{drafts=fields.map(f=>f.read(false));drafts.splice(i,1);draw();onChange();}catch(e){node.querySelector('[data-variant-remove]').textContent=e.message;}};return field;});root.querySelector('[data-variant-add]').onclick=()=>{try{drafts=fields.map(f=>f.read(false));if(drafts.length>=30)throw Error('最多维护 30 条其他描述');drafts.push({variantId:crypto.randomUUID(),text:'',note:'',sourceId,showTogether:true});draw();onChange();}catch(e){root.querySelector('[data-variant-add]').textContent=e.message;}};}
 draw();return {read:(required=true)=>fields.map(f=>f.read(required)),refresh:()=>fields.forEach(f=>f.refresh())};
}
export function openAddonEditor(api){
 const choices=(api.getSourceRows?.()||[]).flatMap(row=>sourceAddonOptions(row).filter(a=>a.text?.trim()).map(a=>({addon:a,label:row.name+' · '+a.text})));
 api.openDialog('编辑加购',`${choices.length?'<label class="field">选用已维护的加购描述<select id="addon-description-choice"><option value="">自定义 / 保留当前描述</option>'+choices.map((v,i)=>`<option value="${i}">${esc(v.label)}</option>`).join('')+'</select></label>':''}<div id="addon-fields"></div><p id="addon-edit-message" class="error" role="status"></p><button id="addon-edit-save" class="primary">保存加购</button>`);
 let fields=mountAddonFields(document.querySelector('#addon-fields'),api);const picker=document.querySelector('#addon-description-choice');if(picker)picker.onchange=()=>{if(picker.value==='')return;fields=mountAddonFields(document.querySelector('#addon-fields'),{...api,initial:choices[Number(picker.value)].addon});};
 document.querySelector('#addon-edit-save').onclick=()=>{try{api.commit(fields.read());}catch(e){document.querySelector('#addon-edit-message').textContent=e.message;}};
}
export function openAddonBatch(api){
 const {openDialog,getConfigs,getCosts}=api,groups=addonGroups(getConfigs());openDialog('批量修改加购描述',`<p class="hint">仅更新本次范围内匹配的加购，其他配件、输出源和模板保留。先预览，再应用。</p><div id="addon-batch-target"></div><div id="addon-batch-fields"></div><label><input type="checkbox" id="addon-batch-pricing"> 同时更新关联商品、数量和加购价（可选）</label><div class="actions"><button id="addon-batch-preview">预览修改</button><button id="addon-batch-apply" class="primary" disabled>应用修改</button></div><pre id="addon-batch-diff"></pre><p id="addon-batch-message" role="status"></p>`);
 const $=s=>document.querySelector(s);let fields,group,plan;const invalidate=()=>{plan=null;$('#addon-batch-apply').disabled=true;$('#addon-batch-diff').textContent='';};
 mountProductSearch($('#addon-batch-target'),{getRows:()=>groups.map((g,i)=>({id:String(i),name:g.example.text||'未填写描述',goodsId:g.example.goodsId||'',group:g})),idKey:'id',label:'要修改的加购',placeholder:'输入加购描述或商品 ID',showEmpty:true,describe:r=>(r.goodsId?'ID '+r.goodsId:'未关联商品')+' · '+r.group.configIds.length+' 套配置',onChange:row=>{invalidate();if(!row){fields=null;$('#addon-batch-fields').innerHTML='';return;}group=row.group;$('#addon-batch-pricing').checked=false;fields=mountAddonFields($('#addon-batch-fields'),{initial:group.example,getCosts,onChange:invalidate,renderStatus:patch=>getConfigs().filter(c=>!c.deletedAt).flatMap(c=>(c.addons||[]).filter(a=>addonKey(a)===group.key).map(a=>`<div><strong>${esc(c.product)} / ${esc(c.name)}</strong>${addonStatusHtml({...a,text:patch.text,...($('#addon-batch-pricing').checked?{goodsId:patch.goodsId,priceCents:patch.priceCents,qty:patch.qty,items:patch.items,originalQty:patch.originalQty}:{})},getCosts(),c.parts||[])}</div>`)).join('')});}});$('#addon-batch-pricing').onchange=()=>{invalidate();fields?.refresh();};
 $('#addon-batch-preview').onclick=()=>{try{if(!fields)throw Error('请选择加购');plan=addonBatchPlan(getConfigs(),group.key,fields.read(false),{updatePricing:$('#addon-batch-pricing').checked,costs:getCosts()});$('#addon-batch-diff').textContent=plan.changes.map(d=>`${d.product} / ${d.name}\n${d.before.addons.map(addonSummary).join('\n')} → ${d.after.addons.map(addonSummary).join('\n')}\n${$('#addon-batch-pricing').checked?'将同时更新关联商品、数量和加购价。':'保留每条原有商品、数量和加购价。'}`).join('\n\n');$('#addon-batch-apply').disabled=!plan.changes.length;$('#addon-batch-message').textContent=`将修改 ${plan.changes.length} 套配置`; }catch(e){invalidate();$('#addon-batch-message').textContent=e.message;}};
 $('#addon-batch-apply').onclick=async()=>{try{if(!plan)return;$('#addon-batch-apply').disabled=true;await api.apply(plan);$('#addon-batch-message').textContent='加购描述已批量保存';plan=null;}catch(e){$('#addon-batch-message').textContent=e.message;}};
}
