import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {build} from 'electron-builder';
import {build as bundle} from 'esbuild';
const root=fileURLToPath(new URL('./',import.meta.url)),workspace=path.dirname(root),version='0.2.21';
const stage=path.join(root,'.desktop-build','app-'+Date.now()),output=path.join(workspace,'release');
await fs.mkdir(path.join(stage,'prototype'),{recursive:true});
for(const e of await fs.readdir(root,{withFileTypes:true}))if(e.isFile()&&/\.(js|mjs|html|css)$/.test(e.name)&&!e.name.startsWith('build-')&&!e.name.startsWith('restore-'))await fs.copyFile(path.join(root,e.name),path.join(stage,'prototype',e.name));
for(const dir of ['local-store','assets','vendor'])await fs.cp(path.join(root,dir),path.join(stage,'prototype',dir),{recursive:true});
// Bundle the pure-JS SQL Server driver so portable users need neither Node nor Python.
await bundle({stdin:{contents:"module.exports = require('mssql');",resolveDir:root},bundle:true,platform:'node',format:'cjs',target:'node24',outfile:path.join(stage,'prototype/vendor/sql-driver.cjs')});
const sqlSource=path.join(stage,'prototype/sql-source.mjs');await fs.writeFile(sqlSource,(await fs.readFile(sqlSource,'utf8')).replace("import('mssql')","import('./vendor/sql-driver.cjs')"));
await fs.cp(path.join(workspace,'shared'),path.join(stage,'shared'),{recursive:true});
await fs.copyFile(path.join(root,'desktop/main.cjs'),path.join(stage,'main.cjs'));
await fs.copyFile(path.join(root,'.env.local'),path.join(stage,'prototype/.env.local'));
await fs.writeFile(path.join(stage,'prototype/seed.json'),JSON.stringify({revision:0,configs:[],templates:[],sourceCatalog:[],costSource:[],caseGallery:[],logs:[],dataVersion:3}));
await fs.writeFile(path.join(stage,'prototype/catalog.json'),'[]');
await fs.writeFile(path.join(stage,'prototype/package.json'),JSON.stringify({type:'module'}));
await fs.writeFile(path.join(stage,'package.json'),JSON.stringify({name:'diy-workbench-desktop',productName:'DIY配置工作台',version,main:'main.cjs',description:'三店配置、共享成本与多人同步工作台',author:'DIY Workbench'}));
await fs.mkdir(output,{recursive:true});
await fs.writeFile(path.join(output,'desktop-build.json'),JSON.stringify({version,stage,businessDataIncluded:false,builtAt:new Date().toISOString()},null,2));
await build({projectDir:stage,config:{appId:'local.diy.workbench',productName:'DIY配置工作台',electronVersion:'44.4.1',electronDist:path.join(root,'node_modules/electron/dist'),directories:{output},asar:true,npmRebuild:false,win:{target:[{target:'portable',arch:['x64']}],icon:path.join(root,'assets/workbench-icon-v1.ico'),signExecutable:false,artifactName:'DIY配置工作台-${version}.${ext}'},portable:{requestExecutionLevel:'user'}}});
console.log(output);
