const palette=[['黑色','#000000'],['深灰','#545454'],['灰色','#737373'],['中灰','#a6a6a6'],['浅灰','#b6b6b6'],['银灰','#d9d9d9'],['白色','#ffffff'],['红色','#ff3131'],['珊瑚红','#ff5757'],['粉色','#ff66c4'],['淡紫','#e2a9f1'],['紫色','#cb6ce6'],['紫罗兰','#8c52ff'],['深紫','#5e17eb'],['青色','#0097b2'],['湖蓝','#0cc0df'],['浅青','#5ce1e6'],['天蓝','#38b6ff'],['蓝紫','#5271ff'],['蓝色','#004aad'],['深蓝','#1800ad'],['绿色','#00bf63'],['草绿','#7ed957'],['浅绿','#c1ff72'],['黄色','#ffde59'],['金黄','#ffbd59'],['橙色','#ff914d'],['橘色','#ff751f']];
const valid=value=>/^#[0-9a-f]{6}$/i.test(value);
const normalize=value=>{const v=value.trim();return /^#?[0-9a-f]{6}$/i.test(v)?'#'+v.replace('#','').toLowerCase():/^#?[0-9a-f]{3}$/i.test(v)?'#'+v.replace('#','').split('').map(c=>c+c).join('').toLowerCase():null;};
const savedKey='diy-poster-colors-v1';
function favorites(){try{return JSON.parse(localStorage.getItem(savedKey)||'[]').filter(valid).slice(-24);}catch{return [];}}
export function installColorPicker(api){
 const panel=document.createElement('dialog');panel.className='color-picker-dialog';panel.setAttribute('aria-label','颜色选择');panel.innerHTML=`<header class="cp-header"><strong id="cp-title">颜色</strong><button class="cp-close" aria-label="关闭颜色面板">×</button></header><div class="cp-search"><input id="cp-search" aria-label="搜索颜色或输入 HEX" placeholder="搜索“蓝色”或输入 #00c4cc"><button id="cp-apply" disabled>应用</button></div><div class="cp-body"><section><h3>此设计中的颜色</h3><div id="cp-used" class="cp-swatches"></div></section><section class="cp-favorites"><h3>收藏颜色 <small>保存在本机</small></h3><div id="cp-saved" class="cp-swatches"></div><button id="cp-save" class="cp-wide">＋ 收藏当前颜色</button><p id="cp-status" role="status"></p></section><section><h3>默认纯色</h3><div id="cp-default" class="cp-swatches"></div><p id="cp-empty" hidden>没有匹配的颜色，可输入 HEX 色值。</p></section><section><h3>自定义颜色</h3><div class="cp-custom"><input id="cp-native" type="color" data-native-color aria-label="选择自定义颜色"><span id="cp-value"></span></div></section></div>`;document.body.append(panel);
 const $=s=>panel.querySelector(s);let target=null,currentColor='#000000';
 const swatches=(el,colors)=>{el.replaceChildren();for(const entry of colors){const [label,color]=Array.isArray(entry)?entry:[entry,entry];const b=document.createElement('button');b.type='button';b.className='cp-swatch';b.style.background=color;b.title=label+' '+color.toUpperCase();b.setAttribute('aria-label',b.title);b.setAttribute('aria-pressed',String(color.toLowerCase()===currentColor.toLowerCase()));b.dataset.color=color;b.onclick=()=>apply(color);el.append(b);}};
 const close=()=>{const input=target,focusHandler=input?.onfocus;if(input)input.onfocus=null;panel.close();if(input)input.onfocus=focusHandler;};$('.cp-close').onclick=close;panel.addEventListener('cancel',e=>{e.preventDefault();close();});
 const apply=color=>{if(!valid(color)||!target?.isConnected){close();return;}api.checkpoint();target.value=color;target.dispatchEvent(new Event('input',{bubbles:true}));target.dispatchEvent(new Event('change',{bubbles:true}));close();};
 const search=()=>{const value=$('#cp-search').value.trim().toLowerCase(),hex=normalize(value);$('#cp-apply').disabled=!hex;const matches=palette.filter(([name,color])=>!value||name.includes(value)||color.includes(value));swatches($('#cp-default'),matches);$('#cp-empty').hidden=!!matches.length;};$('#cp-search').oninput=search;$('#cp-search').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();const hex=normalize(e.target.value);if(hex)apply(hex);}};$('#cp-apply').onclick=()=>apply(normalize($('#cp-search').value));
 $('#cp-save').onclick=()=>{const color=normalize($('#cp-search').value)||currentColor;try{localStorage.setItem(savedKey,JSON.stringify([...new Set([...favorites(),color])].slice(-24)));swatches($('#cp-saved'),favorites());$('#cp-status').textContent='已收藏 '+color.toUpperCase();}catch{$('#cp-status').textContent='浏览器暂时无法保存收藏';}};$('#cp-native').oninput=e=>{const color=e.target.value;$('#cp-search').value=color;$('#cp-value').textContent=color.toUpperCase();search();};
const open=input=>{target=input;currentColor=input.value;const label=input.closest('label');$('#cp-title').textContent=(label?.childNodes[0]?.textContent||input.getAttribute('aria-label')||'颜色').trim();$('#cp-search').value='';$('#cp-status').textContent='';$('#cp-native').value=currentColor;$('#cp-value').textContent=currentColor.toUpperCase();const used=[currentColor,...Object.values(posterPalette(api.current()?.theme)),...(JSON.stringify(api.current()||{}).match(/#[0-9a-f]{6}\b/gi)||[])];swatches($('#cp-used'),[...new Set(used.map(c=>c.toLowerCase()))].slice(0,30));swatches($('#cp-saved'),favorites());search();const rect=input.getBoundingClientRect(),width=Math.min(360,innerWidth-24);panel.style.left=Math.max(12,Math.min(rect.left,innerWidth-width-12))+'px';panel.style.top=Math.max(12,Math.min(rect.top,innerHeight-660))+'px';panel.style.maxHeight=(innerHeight-parseFloat(panel.style.top)-12)+'px';panel.showModal();};
 document.addEventListener('click',e=>{const input=e.target.closest('input[type="color"]:not([data-native-color])');if(!input)return;e.preventDefault();e.stopPropagation();open(input);},true);
 const enhance=()=>{for(const input of document.querySelectorAll('input[type="color"]:not([data-native-color])')){if(input.closest('.color-field-trigger'))continue;const wrapper=document.createElement('span');wrapper.className='color-field-trigger';input.before(wrapper);wrapper.append(input);const value=document.createElement('span');value.className='color-field-value';value.textContent=input.value.toUpperCase();wrapper.append(value);value.onclick=e=>{e.preventDefault();open(input);};input.addEventListener('input',()=>value.textContent=input.value.toUpperCase());input.setAttribute('title','点击打开颜色面板');}};
 new MutationObserver(enhance).observe(document.querySelector('.workspace'),{childList:true,subtree:true});enhance();
}
import {posterPalette} from './core.js';
