import {componentStockHtml} from './component-stock-view.js';
import {parseCostPaste,parseCostPrice} from './cost-paste.js';
import {erpUnitCost} from './core.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const stamp=x=>x?new Date(x).toLocaleString('zh-CN'):'尚未更新';
const money=x=>x==null?'—':Number(x).toFixed(2);
export function openCostEditor(api){let page=0,selected=new Set(),preview=null,busy=false;
 api.openDialog('成本源维护',`<p class="hint">库存与 ERP 成本由右上角“一键同步”更新。含税核算价人工维护，保存后同步到引用该 goods_id 的输出源和配置，并记录时间。</p><div class="cost-source-meta" id="cost-source-meta"></div><div class="source-toolbar"><input id="cost-source-search" type="search" placeholder="搜索 goods_id 或商品名称"><button id="cost-source-paste-toggle">批量粘贴核算价</button></div><div id="cost-source-paste" class="hidden"><p class="hint">支持两列：goods_id＋含税单价；或先勾选商品，再粘贴一列单价（按表格原始顺序）。可带 goods_id / 含税成本表头，空值保留原价；#VALUE! 改用对应 ERP 成本，无可用 ERP 成本时保留原核算价。</p><textarea id="cost-paste-values" placeholder="47538&#9;1400"></textarea><button id="cost-paste-check">预览修改</button><div id="cost-paste-message" class="hint" role="status" aria-live="polite"></div><div id="cost-paste-diff" class="hint"></div><button id="cost-paste-apply" class="primary" disabled>保存并更新引用配置</button></div><div class="cost-source-wrap"><table class="cost-source-table"><thead><tr><th><input id="cost-source-all" type="checkbox" aria-label="全选搜索结果"></th><th>goods_id</th><th>商品名称</th><th>可销库存</th><th>ERP 成本</th><th>含税核算单价</th><th>核算价更新时间</th><th></th></tr></thead><tbody id="cost-source-rows"></tbody></table></div><div class="source-pagination"><button id="cost-prev">上一页</button><span id="cost-page"></span><button id="cost-next">下一页</button></div><div id="cost-message" class="hint" role="status"></div>`);$('#dialog').classList.add('cost-dialog');
 const filtered=(source=api.getRows())=>{const q=$('#cost-source-search').value.toLowerCase().trim();return source.filter(r=>[r.goodsId,r.name].join(' ').toLowerCase().includes(q));};
 function draw(){const source=api.getRows(),stocks=new Map();for(const row of source){if(!stocks.has(row.goodsId))stocks.set(row.goodsId,[]);stocks.get(row.goodsId).push(row);}const rows=filtered(source),pages=Math.max(1,Math.ceil(rows.length/30));page=Math.min(page,pages-1);const last=source.reduce((last,row)=>row.taxUpdatedAt>last?row.taxUpdatedAt:last,'');$('#cost-source-meta').textContent=`最近人工维护：${stamp(last)} ｜ 库存 / ERP：${stamp(api.lastErp())}`;$('#cost-source-rows').innerHTML=rows.slice(page*30,page*30+30).map(r=>{const unit=erpUnitCost(r);return `<tr><td><input type="checkbox" data-cost-choice="${esc(r.goodsId)}" ${selected.has(r.goodsId)?'checked':''}></td><td>${esc(r.goodsId)}</td><td>${esc(r.name)}</td><td>${componentStockHtml(r,stocks)}</td><td>${unit.cents===null?'待补成本':money(unit.cents/100)}${unit.fallback?'<small class="erp-fallback-note">核算成本代入 · ERP价格未识别</small>':''}</td><td><input data-manual-price="${esc(r.goodsId)}" type="number" min="0" step=".01" value="${r.tax??''}" aria-label="${esc(r.goodsId)} 含税核算单价"></td><td><small>${stamp(r.taxUpdatedAt)}</small></td><td><button data-cost-save="${esc(r.goodsId)}">保存</button></td></tr>`;}).join('');$('#cost-page').textContent=`${page+1} / ${pages} · ${rows.length} 条 · 已选 ${selected.size} 条`;$('#cost-prev').disabled=!page;$('#cost-next').disabled=page===pages-1;const all=$('#cost-source-all');all.checked=rows.length>0&&rows.every(r=>selected.has(r.goodsId));all.indeterminate=rows.some(r=>selected.has(r.goodsId))&&!all.checked;$$('[data-cost-choice]').forEach(c=>c.onchange=()=>{c.checked?selected.add(c.dataset.costChoice):selected.delete(c.dataset.costChoice);preview=null;$('#cost-paste-apply').disabled=true;draw();});$$('[data-cost-save]').forEach(b=>b.onclick=async()=>{if(busy)return;try{const value=$$('[data-manual-price]').find(i=>i.dataset.manualPrice===b.dataset.costSave).value;await commit([{goodsId:b.dataset.costSave,tax:parsePrice(value)}]);}catch(e){message(e.message,true);}});}
 function message(text,error=false){for(const id of ['cost-message','cost-paste-message']){const el=$('#'+id);if(el){el.textContent=text;el.classList.toggle('danger',error);}}}
 const parsePrice=parseCostPrice;
 async function commit(entries){if(busy)return;busy=true;message(`正在保存 ${entries.length} 条核算价并更新引用配置，请稍候…`);const input=$('#cost-paste-values');input.disabled=true;$$('#dialog-body button').forEach(b=>b.disabled=true);try{await new Promise(resolve=>setTimeout(resolve,0));const count=await api.apply(entries);if(!$('#cost-source-rows'))return;draw();message(`已更新 ${entries.length} 条核算价，${count} 套配置已重新核算；更新时间已记录。`);}catch(e){message('保存失败：'+e.message,true);}finally{busy=false;if($('#cost-source-rows')){$('#cost-paste-values').disabled=false;$$('#dialog-body button').forEach(b=>b.disabled=false);preview=null;$('#cost-paste-apply').disabled=true;draw();}}}
 $('#cost-source-search').oninput=()=>{page=0;draw();};$('#cost-prev').onclick=()=>{page--;draw();};$('#cost-next').onclick=()=>{page++;draw();};$('#cost-source-all').onchange=e=>{filtered().forEach(r=>e.target.checked?selected.add(r.goodsId):selected.delete(r.goodsId));preview=null;$('#cost-paste-apply').disabled=true;draw();};
 $('#cost-source-paste-toggle').onclick=()=>$('#cost-source-paste').classList.toggle('hidden');$('#cost-paste-values').oninput=()=>{preview=null;$('#cost-paste-apply').disabled=true;$('#cost-paste-diff').textContent='';message('粘贴内容已更改，请点击“预览修改”。');};
 $('#cost-paste-check').onclick=()=>{preview=null;$('#cost-paste-apply').disabled=true;$('#cost-paste-diff').textContent='';try{
 const rows=api.getRows(),lookup=new Map(rows.map(r=>[r.goodsId,r]));
 const result=parseCostPaste($('#cost-paste-values').value,rows,[...selected]);preview=result.entries;const fallbackIds=new Set(result.erpFallbacks.map(r=>r.goodsId));
 const limit=100;$('#cost-paste-diff').textContent=preview.slice(0,limit).map(e=>`${e.goodsId} ${lookup.get(e.goodsId).name}：${money(lookup.get(e.goodsId).tax)} → ${money(e.tax)}${fallbackIds.has(e.goodsId)?'（#VALUE! 改用 ERP 成本）':''}`).join('\n')+(preview.length>limit?`\n…仅展示前 ${limit} 条，保存将应用全部 ${preview.length} 条。`:'');
 message(`可保存 ${preview.length} 条；已识别 ${result.headers} 行表头，${result.blank} 行空值保留，${result.valueErrors.length} 行 #VALUE! 中 ${result.erpFallbacks.length} 条改用 ERP 成本，${result.duplicates} 行相同重复价合并。`+(result.unavailableErp.length?` ${result.unavailableErp.length} 行 ERP 成本不可用，保留原核算价：${result.unavailableErp.slice(0,10).map(r=>r.goodsId).join('、')}${result.unavailableErp.length>10?'…':''}`:'')+(result.unmatched.length?` ${result.unmatched.length} 个 ID 未匹配，不会更新：${result.unmatched.slice(0,10).map(r=>r.goodsId).join('、')}${result.unmatched.length>10?'…':''}`:''));
 $('#cost-paste-apply').textContent=`保存 ${preview.length} 条并更新引用配置`;$('#cost-paste-apply').disabled=false;
 }catch(e){message(e.message,true);}};
 $('#cost-paste-apply').onclick=()=>preview&&commit(preview);draw();
}
