import {allConfigParts} from './actual-parts.js';
import {isSpecialComponent,normalizeSpecialComponent} from './special-components.js';
import {excludedComponent} from './component-policy.js';
import {clone} from './core.js';
import {sourceCatalog} from './source.js';

export function costRows(catalog,saved=[]){const result=clone(saved.filter(r=>!excludedComponent(r))),seen=new Set(result.map(r=>r.goodsId));for(const r of catalog){if(isSpecialComponent(r)||!r.goodsId||seen.has(r.goodsId)||excludedComponent(r))continue;const same=catalog.filter(x=>x.goodsId===r.goodsId);const tax=new Set(same.map(x=>x.tax));result.push({goodsId:r.goodsId,name:r.originalName||r.name,erp:r.erp??null,erpMissing:r.erpMissing??false,erpUnknown:r.erpUnknown??(r.erp==null),tax:tax.size===1?r.tax??null:null,stockAvailable:r.stockAvailable??null,taxUpdatedAt:r.taxUpdatedAt||null,erpUpdatedAt:r.erpUpdatedAt||null});seen.add(r.goodsId);}return result;}
export function validateSnapshot(data){if(data.complete!==true||!Array.isArray(data.rows)||!data.rows.length||data.rows.length!==data.total||data.rows.length>100000)throw Error('ERP 分页不完整或返回空数据，已保留旧数据');const ids=new Set();for(const r of data.rows){if(!r||typeof r.goodsId!=='string'||!/^\d{1,20}$/.test(r.goodsId)||r.goodsId==='0'||ids.has(r.goodsId)||typeof r.name!=='string'||!r.name.trim())throw Error('ERP 商品 ID 缺失或重复');ids.add(r.goodsId);if(r.stockAvailable!==null&&!Number.isFinite(r.stockAvailable))throw Error('ERP 可销库存字段无效');if(r.erp!==null&&(!Number.isFinite(r.erp)||r.erp<0))throw Error('ERP 成本字段无效');}return data.rows;}
export function mergeErp(state,rows,base,at){const next=clone(state);next.sourceCatalog=sourceCatalog(next.sourceCatalog||base);next.costSource=costRows(next.sourceCatalog,next.costSource||[]);const costs=new Map(next.costSource.map(r=>[r.goodsId,r]));const map=new Map(rows.map(r=>[r.goodsId,r]));for(const row of rows){let old=costs.get(row.goodsId);if(!old){if(excludedComponent(row))continue;old={goodsId:row.goodsId,name:row.name,tax:null,taxUpdatedAt:null,erp:null};next.costSource.push(old);costs.set(row.goodsId,old);}old.name=row.name;}
 const update=record=>{if(isSpecialComponent(record)){Object.assign(record,normalizeSpecialComponent(record));return false;}const r=map.get(record.goodsId);if(!r){record.erpMissing=true;return false;}record.erpName=r.name;record.erpMissing=false;record.stockAvailable=r.stockAvailable;record.stockUpdatedAt=at;record.erpUnknown=r.erp===null;if(r.erp!==null){record.erp=r.erp;record.erpUpdatedAt=at;}return true;};
 next.costSource.forEach(update);next.costSource=next.costSource.filter(r=>!excludedComponent(r));let matched=0;next.sourceCatalog.forEach(r=>{if(update(r))matched++;});const configIds=[];for(const c of next.configs){if(c.deletedAt)continue;let changed=false;for(const p of allConfigParts(c))if(p.goodsId&&update(p))changed=true;if(changed){c.erpImportedAt=at;configIds.push(c.id);}}return{next,matched,unmatched:next.sourceCatalog.length-matched,excluded:rows.filter(excludedComponent).length,configIds};}
export function applyManualCosts(state,entries,at=new Date().toISOString()){const map=new Map(state.costSource.map(r=>[r.goodsId,r]));const ids=new Set();for(const item of entries){if(ids.has(item.goodsId)||!map.has(item.goodsId)||item.tax!==null&&(!Number.isFinite(item.tax)||item.tax<0))throw Error('成本行重复、未匹配或单价无效');ids.add(item.goodsId);}for(const item of entries){Object.assign(map.get(item.goodsId),{tax:item.tax,taxUpdatedAt:at});}for(const r of state.sourceCatalog)if(ids.has(r.goodsId))Object.assign(r,{tax:map.get(r.goodsId).tax,taxUpdatedAt:at});const changed=[];for(const c of state.configs){if(c.deletedAt)continue;let hit=false;for(const p of allConfigParts(c))if(ids.has(p.goodsId)){p.tax=map.get(p.goodsId).tax;hit=true;}if(hit){c.taxUpdatedAt=at;changed.push(c.id);}}return changed;}

export const browserErpScope=info=>info?.browserScope||(info?.scope?.startsWith('sql:')?null:info?.scope);
export class ErpJobs{
 constructor(getScope){this.getScope=getScope;this.job=null;this.connection=null;}
 status(){if(this.job&&['waiting','running'].includes(this.job.status)&&Date.now()>this.job.expiresAt){this.job.status='failed';this.job.error='ERP 连接或采集超时，已保留旧数据';}return{job:this.job?{id:this.job.id,status:this.job.status,startedAt:this.job.startedAt,completedAt:this.job.completedAt,error:this.job.error,progress:this.job.progress,result:this.job.result}:null,connection:this.connection&&Date.now()-this.connection.seenAt<25000?{account:this.connection.account,warehouse:this.connection.warehouse,depotId:this.connection.depotId}:null};}
 start(){this.status();if(this.job&&['waiting','running'].includes(this.job.status))return this.status();this.job={id:crypto.randomUUID(),status:'waiting',startedAt:new Date().toISOString(),expiresAt:Date.now()+120000};return this.status();}
 identity(data){if(typeof data.clientId!=='string'||!data.clientId||data.clientId.length>100||typeof data.account!=='string'||!data.account.trim()||data.account.length>100||data.warehouse!=='公司大库'||!/^\d+$/.test(data.depotId))throw Error('请先核对 ERP 顶栏账号与公司大库');const scope=`https://cqzs.3cerp.com|${data.account}|${data.depotId}`;if(this.getScope()&&this.getScope()!==scope)throw Error('ERP 账号或仓库与上次同步不一致，已停止同步');return scope;}
 poll(data){const scope=this.identity(data);this.status();this.connection={...data,seenAt:Date.now()};const j=this.job;if(!j||!['waiting','running'].includes(j.status)||j.status==='running'&&j.clientId!==data.clientId)return{job:null};if(j.status==='waiting'){Object.assign(j,{status:'running',clientId:data.clientId,scope,token:crypto.randomUUID(),expiresAt:Date.now()+180000});}return{job:{id:j.id,token:j.token}};}
 verify(data){this.status();const j=this.job;const scope=this.identity(data);if(!j||j.status!=='running'||j.id!==data.jobId||j.token!==data.token||j.clientId!==data.clientId||j.scope!==scope)throw Error('同步任务已过期或不属于当前 ERP 页面');return j;}
 progress(data){const j=this.verify(data);j.expiresAt=Date.now()+180000;j.progress=String(data.progress||'正在读取').slice(0,100);return{ok:true};}
 fail(data){const j=this.verify(data);j.status='failed';j.error=String(data.error||'ERP 采集失败').slice(0,200);return{ok:true};}
}
