import {bindSqlSync} from './sql-sync-ui.js';
const $=s=>document.querySelector(s);
export function bindErpSync(api){let timer=null,watching=null;let sourceMode=localStorage.getItem('diy-inventory-source-mode')||'company-sql';const sql=bindSqlSync({...api,receive:async result=>{await api.receive(result);header(await request('/api/erp-sync/status'));}});
 const request=async(path,data)=>{const r=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const value=await r.json();if(!r.ok)throw Error(value.error||'同步服务不可用');return value;};
 function header(status){$('#erp-last').textContent=status.lastSuccess?.stockSource==='company-sql'?'SQL 库存 '+new Date(status.lastSuccess.stockUpdatedAt).toLocaleString('zh-CN'):status.lastSuccess?.updatedAt?'上次同步 '+new Date(status.lastSuccess.updatedAt).toLocaleString('zh-CN'):'库存 / ERP 尚未同步';const running=sourceMode==='browser-script'&&['waiting','running'].includes(status.job?.status);$('#erp-sync').disabled=running;$('#erp-sync').textContent=running?status.job.status==='waiting'?'等待 ERP 连接…':'正在同步…':sourceMode==='company-sql'?'ERP同步':'ERP同步';}
 function setup(){api.openDialog('连接 ERP 同步',`<p class="hint">库存同步支持两种来源：公司数据库用于在公司同步，脚本抓取用于不在公司时同步。公司数据库可直接读取公司大库可销库存；脚本同步继续保留 ERP 成本采集。桌面版请安装本窗口提供的脚本，它会连接当前工作台。</p><label class="field">库存来源<select id="inventory-source"><option value="browser-script">脚本抓取（当前可用）</option><option value="company-sql">公司数据库（SQL 库存）</option></select></label><ol class="hint"><li><a href="/workbench-erp.user.js" target="_blank">打开并安装 ERP 同步脚本</a>，也可下载后导入脚本猫。</li><li>在已登录的 ERP 中打开“分库库存”，选择“公司大库”，显示成本单价列。</li><li>点击 ERP 页面右下角“工作台同步：点击连接”，填写顶栏显示的账号姓名，并核对成本单价列。</li><li>保持 ERP 页面打开，回工作台点击右上角“ERP同步”。</li></ol><div class="actions"><button id="erp-open-sql" class="primary">打开 SQL 连接</button><a href="/workbench-erp.user.js" download="workbench-erp.user.js">下载脚本</a><button id="erp-copy-script">复制脚本</button><button id="erp-setup-close" class="primary">知道了</button></div><p id="erp-job-message" class="hint" role="status">${watching?'正在等待 ERP 页面连接。':'连接后即可同步。'}</p>`);$('#inventory-source').value=sourceMode;$('#inventory-source').onchange=e=>{sourceMode=e.target.value;localStorage.setItem('diy-inventory-source-mode',sourceMode);$('#erp-sync').textContent='ERP同步';$('#erp-sync').disabled=false;if(sourceMode==='company-sql'){clearTimeout(timer);watching=null;sql.setup();}};$('#erp-open-sql').onclick=()=>{sourceMode='company-sql';localStorage.setItem('diy-inventory-source-mode',sourceMode);clearTimeout(timer);watching=null;$('#erp-sync').disabled=false;$('#erp-sync').textContent='ERP同步';sql.setup();};$('#erp-setup-close').onclick=()=>$('#dialog').close();$('#erp-copy-script').onclick=async()=>{try{const text=await(await fetch('/workbench-erp.user.js')).text();await navigator.clipboard.writeText(text);$('#erp-job-message').textContent='脚本已复制，请粘贴到脚本猫的新脚本中保存。';}catch{$('#erp-job-message').textContent='复制未成功，请使用下载脚本。';}};}
 async function poll(){try{const s=await request('/api/erp-sync/status');header(s);const j=s.job;if($('#erp-job-message'))$('#erp-job-message').textContent=j?.progress||(j?.status==='waiting'?'等待 ERP 页面连接…':'');if(j?.id===watching&&j.status==='complete'){watching=null;await api.receive(j.result);api.toast(`同步完成：${j.result.total} 条 ERP 商品，自动排除 ${j.result.excluded||0} 条带星号配件，匹配 ${j.result.matched} 条输出源，未匹配 ${j.result.unmatched} 条。`);if($('#erp-job-message'))$('#erp-job-message').textContent='同步成功，人工核算价保留。';return;}if(j?.id===watching&&j.status==='failed'){watching=null;api.toast(j.error||'同步失败，已保留旧数据');if($('#erp-job-message'))$('#erp-job-message').textContent=j.error;return;}if(watching)timer=setTimeout(poll,1500);}catch(e){watching=null;$('#erp-sync').disabled=false;$('#erp-sync').textContent='ERP同步';api.toast(e.message);}}
 $('#erp-setup').onclick=setup;$('#erp-sync').onclick=async()=>{if(sourceMode==='company-sql'){sql.setup();return;}try{await api.flush();const s=await request('/api/erp-sync/start',{operator:api.operator()});watching=s.job.id;header(s);clearTimeout(timer);if(!s.connection)setup();poll();}catch(e){api.toast(e.message);}};
 request('/api/erp-sync/status').then(s=>{header(s);if(sourceMode==='browser-script'&&['waiting','running'].includes(s.job?.status)){watching=s.job.id;poll();}}).catch(()=>{$('#erp-last').textContent='同步服务未连接';});
}
