import {mountProductSearch} from './product-search.js';
import {clone,productGroups} from './core.js';
import {replaceSourcePart} from './source.js';
import {renderPoster} from './poster.js';
import {makeZip} from './zip.js';

const key=p=>String(p.goodsId||'').trim()&&String(p.goodsId)!=='0'?`id:${p.goodsId}`:`name:${p.name}`;
export function findPartUsage(configs,query){
 const q=query.trim().toLowerCase(),found=new Map();if(!q)return [];
 for(const c of configs.filter(c=>!c.deletedAt))for(const p of c.parts){if(!p.name||![p.name,p.goodsId].some(v=>String(v||'').toLowerCase().includes(q)))continue;const k=key(p);if(!found.has(k))found.set(k,{key:k,goodsId:p.goodsId,name:p.name,ids:new Set()});found.get(k).ids.add(c.id);}
 return [...found.values()].map(r=>({...r,count:r.ids.size,ids:undefined}));
}
export function usageGroups(configs,partKey){return productGroups(configs.filter(c=>!c.deletedAt)).map(g=>({...g,matches:g.configs.filter(c=>c.parts.some(p=>key(p)===partKey))})).filter(g=>g.matches.length);}
export function replacementPlan(configs,partKey,productIds,replacement,qty){
 if(!replacement||replacement.deletedAt)throw Error('请选择新的配件');if(qty!==null&&(!Number.isInteger(qty)||qty<1))throw Error('数量必须是正整数，留空则保留原数量');
 const groups=usageGroups(configs,partKey).filter(g=>productIds.includes(g.id)),changes=[];
 for(const g of groups)for(const c of g.matches){const after=clone(c);for(let i=0;i<after.parts.length;i++)if(key(after.parts[i])===partKey){replaceSourcePart(after,i,replacement);if(qty!==null)after.parts[i].qty=qty;}if(JSON.stringify(c)!==JSON.stringify(after))changes.push({id:c.id,productId:g.id,name:c.name,product:g.name,before:clone(c),after});}
 return {changes,productIds:groups.map(g=>g.id),replacement:clone(replacement),partKey};
}
export function applyReplacement(plan,configs){
 const targets=plan.changes.map(change=>{const c=configs.find(c=>c.id===change.id);if(!c||JSON.stringify(c)!==JSON.stringify(change.before))throw Error('配置已变化，请重新预览');return c;});
 targets.forEach((c,i)=>Object.assign(c,clone(plan.changes[i].after)));return targets.map(c=>c.id);
}
const safe=s=>String(s).replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').replace(/[. ]+$/g,'').slice(0,90)||'未命名';
export function exportEntries(configs,productIds){
 const groups=productGroups(configs.filter(c=>!c.deletedAt)).filter(g=>productIds.includes(g.id)),entries=[],folders=new Set(),paths=new Set();
 for(const g of groups){if(g.configs.some(c=>!/^\d+$/.test(c.spu||'')))throw Error(`“${g.name}”缺少有效 SPU，请先补齐，或取消自动导出`);let folder=safe(`${g.configs[0].spu}_${g.name}`),base=folder,n=1;while(folders.has(folder))folder=`${base}_${++n}`;folders.add(folder);
  g.configs.forEach((c,i)=>{const number=/^配置\s*([\d一二三四五六七八九十百]+)$/.exec(c.name||'');const label=number?`配置${number[1]}`:`配置${i+1}`;for(const [layout,dir] of [['long','配置清单图'],['square','SKU图']]){const name=`${folder}/${dir}/${safe(c.spu+'_'+label)}.png`;if(paths.has(name))throw Error(`“${g.name}”存在重复配置编号，请先修改配置名称`);paths.add(name);entries.push({name,config:{...clone(c),layout}});}});
 }return entries;
}

export function openGlobalBatch(api){
 const {openDialog,esc,toast,getConfigs,getCatalog,apply,save,download}=api;
 openDialog('全局批量修改',`<button id="global-addons">批量修改本店加购描述</button><p class="hint">查询所有链接中使用该配件的配置，勾选链接后统一替换。只修改命中的配件，原数量默认保留。</p><label class="field">查找原配件<input id="global-query" placeholder="输入配件名称或 ERP ID"></label><div id="global-candidates" class="global-list"></div><div id="global-work" class="hidden"><div class="global-toolbar"><strong id="global-summary"></strong><label><input id="global-all" type="checkbox" checked> 全选链接</label></div><div id="global-links" class="global-list"></div><div id="global-product-search"></div><label class="field">统一数量（留空保留各配置原数量）<input id="global-qty" type="number" min="1" step="1" placeholder="保留原数量"></label><label class="global-export"><input id="global-export" type="checkbox"> 修改后自动导出所选链接的全部配置清单图和 1:1 SKU 图（1400px）</label><p class="hint">每个链接一个文件夹；其内按「配置清单图 / SKU图」分开，图片名为 SPU_配置编号.png。沿用各配置的配色和机箱图片。</p><div class="actions"><button id="global-preview">预览统一修改</button><button id="global-apply" class="primary" disabled>应用修改</button></div><div id="global-diff" class="hint"></div></div><p id="global-status" role="status" class="hint"></p><button id="global-retry" class="hidden">重新保存并导出 ZIP</button>`);
 const $=s=>document.querySelector(s),root=$('#global-status');let partKey='',groups=[],plan=null,busy=false,exportIds=null,retryExport=false;
 $('#global-addons').onclick=()=>api.openAddons();
 const dialog=root.closest('dialog'),controller=new AbortController();dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();},{signal:controller.signal});dialog.addEventListener('close',()=>controller.abort(),{once:true,signal:controller.signal});
 const status=message=>{if(root.isConnected)root.textContent=message;};
 const invalidate=()=>{plan=null;$('#global-apply').disabled=true;$('#global-diff').textContent='';};
 const picked=()=>[...document.querySelectorAll('[data-global-link]:checked')].map(el=>el.value);
 const updateSummary=()=>{const selected=groups.filter(g=>picked().includes(g.id));$('#global-summary').textContent=`已选 ${selected.length} 个链接 · ${selected.reduce((n,g)=>n+g.matches.length,0)} 套命中配置`;$('#global-all').checked=selected.length===groups.length;$('#global-all').indeterminate=selected.length>0&&selected.length<groups.length;invalidate();};
 $('#global-query').oninput=()=>{if(busy)return;invalidate();$('#global-work').classList.add('hidden');const rows=findPartUsage(getConfigs(),$('#global-query').value);$('#global-candidates').innerHTML=rows.slice(0,80).map((r,i)=>`<button data-global-part="${i}"><strong>${esc(r.name)}</strong><small>ERP ID ${esc(r.goodsId||'无')} · ${r.count} 套配置</small></button>`).join('');status(rows.length>80?'候选超过 80 项，请输入更完整名称或 ID':rows.length?'请选择要统一修改的原配件':'没有匹配配件');document.querySelectorAll('[data-global-part]').forEach(el=>el.onclick=()=>{partKey=rows[Number(el.dataset.globalPart)].key;groups=usageGroups(getConfigs(),partKey);$('#global-candidates').innerHTML=`<p class="hint">原配件：${esc(rows[Number(el.dataset.globalPart)].name)} · ${esc(partKey)}</p>`;$('#global-work').classList.remove('hidden');$('#global-links').innerHTML=groups.map(g=>`<label><input type="checkbox" data-global-link value="${esc(g.id)}" checked><span><strong>${esc(g.name)}</strong><small>SPU ${esc(g.spu||'未填写')} · ${g.matches.length}/${g.configs.length} 套命中：${esc(g.matches.map(c=>c.name).join('、'))}</small></span></label>`).join('');document.querySelectorAll('[data-global-link]').forEach(el=>el.onchange=updateSummary);updateSummary();status('已列出所有关联链接，请选择新配件并预览');});};
 $('#global-all').onchange=e=>{document.querySelectorAll('[data-global-link]').forEach(el=>el.checked=e.target.checked);updateSummary();};
 const replacementPicker=mountProductSearch($('#global-product-search'),{getRows:getCatalog,idKey:'sourceId',label:'查找新配件',inputId:'global-new-query',describe:r=>'ERP ID '+r.goodsId+' · 核算 '+(r.tax??'待补'),onChange:invalidate});
 for(const id of ['global-qty','global-export'])$('#'+id).onchange=invalidate;
 const currentReplacement=()=>replacementPicker.row();
 $('#global-preview').onclick=()=>{try{plan=replacementPlan(getConfigs(),partKey,picked(),currentReplacement(),$('#global-qty').value===''?null:Number($('#global-qty').value));if($('#global-export').checked)exportEntries(getConfigs(),plan.productIds);$('#global-diff').textContent=plan.changes.map(c=>{const rows=c.before.parts.flatMap((p,i)=>key(p)===partKey?[`${p.slot}：${p.name} ×${p.qty} → ${c.after.parts[i].name} ×${c.after.parts[i].qty}`]:[]);if(JSON.stringify(c.before.addons)!==JSON.stringify(c.after.addons))rows.push('关联加购：'+(c.before.addons.map(a=>a.text).join('；')||'无')+' → '+(c.after.addons.map(a=>a.text).join('；')||'无'));return `${c.product} / ${c.name}\n${rows.join('\n')}`;}).join('\n\n');$('#global-apply').disabled=!plan.changes.length;status(`将修改 ${plan.changes.length} 套配置${$('#global-export').checked?`，导出所选链接全部 ${exportEntries(getConfigs(),plan.productIds).length} 张图片`:''}。请核对下方差异后应用。`);}catch(e){invalidate();status(e.message);}};
 const exportZip=async()=>{await save();const entries=exportEntries(getConfigs(),exportIds),files=[],failures=[];for(const [i,entry] of entries.entries()){status(`配置已保存，正在导出 ${i+1}/${entries.length}：${entry.name}`);try{const r=await renderPoster(entry.config,1400);if(r.overflow)throw Error('1:1 图片内容超出，请调整模块或字号');const blob=await new Promise(resolve=>r.canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('图片生成失败');files.push({name:entry.name,bytes:new Uint8Array(await blob.arrayBuffer())});}catch(e){failures.push({name:entry.name,error:e.message});}}if(!files.length)throw Error('全部图片生成失败：'+failures.map(f=>f.error).join('；'));files.push({name:'导出结果.json',bytes:new TextEncoder().encode(JSON.stringify({createdAt:new Date().toISOString(),success:files.map(f=>f.name),failures},null,2))});download(makeZip(files),`批量修改配置图_${Date.now()}.zip`);status(`已保存修改并导出 ${files.length-1} 张图片，失败 ${failures.length} 张。${failures.length?'详情见 ZIP 内导出结果.json。':''}`);};
 const lock=value=>{busy=value;if(root.isConnected){dialog.querySelector('.close').disabled=value;document.querySelectorAll('#dialog-body input,#dialog-body select,#dialog-body button').forEach(el=>el.disabled=value);}};
 $('#global-apply').onclick=async()=>{if(busy||!plan)return;const approved=plan,auto=$('#global-export').checked;try{if(JSON.stringify(currentReplacement())!==JSON.stringify(approved.replacement))throw Error('新配件资料已变化，请重新预览');if(auto)exportEntries(getConfigs(),approved.productIds);applyReplacement(approved,clone(getConfigs()));lock(true);exportIds=approved.productIds;retryExport=auto;await apply(approved);plan=null;if(auto)await exportZip();else status(`已统一修改并保存 ${approved.changes.length} 套配置`);if(root.isConnected){$('#global-retry').classList.toggle('hidden',!auto);$('#global-retry').textContent='再次导出 ZIP';}}catch(e){status(e.message);toast(e.message);if(exportIds&&root.isConnected){$('#global-retry').classList.remove('hidden');$('#global-retry').textContent=retryExport?'重新保存并导出 ZIP':'重新保存修改';}}finally{lock(false);if(root.isConnected)invalidate();}};
 $('#global-retry').onclick=async()=>{try{lock(true);if(retryExport)await exportZip();else{await save();status('修改已保存');$('#global-retry').classList.add('hidden');}}catch(e){status(e.message);}finally{lock(false);if(root.isConnected)invalidate();}};
}
