import {mountSourceSync} from './source-sync-ui.js';
import {mountShopAddons} from './shop-addon-ui.js';
import {excludedComponent} from './component-policy.js';
import {clone} from './core.js';
import {sourceAddon,sourceAddonFields,validateAddon,addonCheck,sourceAddonOptions} from './addon-data.js';
import {addonStatusHtml} from './addon-ui.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const labels={name:'显示名称',tax:'含税核算单价',upgrade:'升级文案',addon:'加购文案'};

export function openSourceEditor(api){
 let selectedId=null,page=0,draft=null,preview=null,busy=false,showDeleted=false,addonFields,sourceSync;
 api.openDialog('本店输出源维护',`<section id="source-sync-top" class="source-sync-top"></section><p class="hint">显示名称、升级文案属于当前店铺；加购集中展示三店，勾选要修改的店铺；含税核算单价按 ERP ID 与三店共用。核算价格为单件价，加购文案不计入整机成本。</p><div class="source-toolbar"><input id="source-search" type="search" placeholder="搜索显示名称、ERP ID 或升级文案" aria-label="搜索输出源"><button id="source-addon-check">一键检查加购差价</button><button id="source-deleted">已删除</button><button id="source-new">＋ 新增配件</button></div><div id="source-addon-report"></div><div class="source-workspace"><div class="source-list-panel"><div id="source-count" class="hint"></div><div id="source-list"></div><div class="source-pagination"><button id="source-prev">上一页</button><span id="source-page"></span><button id="source-next">下一页</button></div></div><div id="source-detail"><p class="hint">从左侧选择需要维护的配件。</p></div></div><div id="source-message" role="status" class="hint"></div>`);
 $('#dialog').classList.add('source-dialog');
 const message=text=>$('#source-message').textContent=text;
 sourceSync=mountSourceSync($('#source-sync-top'),{getRows:api.getRows,getConfigs:api.getConfigs,shopId:api.shopId,isEdited:()=>!!draft&&isEdited(),flush:api.flush,apply:api.applySync,saveImage:api.saveImage,download:api.download,message});
 const filtered=()=>{const q=$('#source-search').value.trim().toLowerCase();return api.getRows().filter(r=>!!r.deletedAt===showDeleted&&[r.name,r.goodsId,r.upgrade].join(' ').toLowerCase().includes(q));};
 function list(){const rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/24));page=Math.min(page,pages-1);$('#source-count').textContent=`共 ${api.getRows().filter(r=>!r.deletedAt).length} 条在用，匹配 ${rows.length} 条`;$('#source-list').innerHTML=rows.slice(page*24,page*24+24).map(r=>`<button class="source-item ${r.sourceId===selectedId?'active':''}" data-source-id="${esc(r.sourceId)}"><strong>${esc(r.name)}</strong><small>ID ${esc(r.goodsId)} · 核算 ${r.tax==null?'待填':'¥'+Number(r.tax).toFixed(2)}</small></button>`).join('')||'<p class="hint">没有匹配项。</p>';$('#source-page').textContent=`${page+1} / ${pages}`;$('#source-prev').disabled=page===0;$('#source-next').disabled=page===pages-1;$$('[data-source-id]').forEach(b=>b.onclick=()=>{if(busy)return;if(draft&&isEdited()){message('当前配件有未保存修改，请先保存，或点击“重置修改”。');return;}select(api.getRows().find(r=>r.sourceId===b.dataset.sourceId));});}
 function isEdited(){try{return draft&&!draft.deletedAt&&(addonFields.isDirty()||JSON.stringify(read(false))!==JSON.stringify(draft));}catch{return true;}}
 function invalidate(){preview=null;sourceSync?.invalidate();}
 function read(validate=true){const addon=addonFields.read(false);const row={...clone(draft),...sourceAddonFields(addon),goodsId:$('#source-id').value.trim(),name:$('#source-name').value.trim(),tax:$('#source-tax').value===''?null:Number($('#source-tax').value),upgrade:$('#source-upgrade').value.trim()};if(validate){if(addon.text.trim())validateAddon(addon,{required:true,costs:api.getCosts()});if(!/^\d+$/.test(row.goodsId))throw Error('请填写准确的数字 ERP ID');if(!row.name)throw Error('请填写产品显示名称');if(excludedComponent(row)||api.getCosts().some(r=>r.goodsId===row.goodsId&&excludedComponent(r)))throw Error('带 * 或 *! 标记的配件不可加入输出源');if(row.tax!==null&&(!Number.isFinite(row.tax)||row.tax<0||!/^\d+(\.\d{1,2})?$/.test($('#source-tax').value)))throw Error('核算单价须为非负金额，最多两位小数');if(!selectedId&&api.getRows().some(r=>r.goodsId===row.goodsId))throw Error('该 ERP ID 已存在，请搜索后编辑对应记录');}return row;}
 async function commit(row,ids,keys){busy=true;$$('#source-detail button').forEach(b=>b.disabled=true);try{const count=await api.apply(row,ids,keys,addonFields.changes().filter(c=>c.sourceId!==row.sourceId));if(!$('#source-detail'))return;select(api.getRows().find(r=>r.sourceId===row.sourceId));message(count?`输出源已保存，已同步 ${count} 套配置；图片状态可在配置预览中查看。`:'输出源已保存，下次选用该配件时使用新资料。');}catch(e){if(!$('#source-detail'))return;message('保存失败：'+e.message);$('#source-save').disabled=false;$('#source-check').disabled=false;$('#source-reset').disabled=false;}finally{busy=false;}}
 function select(row){selectedId=api.getRows().some(r=>r.sourceId===row.sourceId)?row.sourceId:null;draft={...clone(row),...sourceAddonFields(sourceAddon(row))};invalidate();if(row.deletedAt){$('#source-detail').innerHTML=`<h3>${esc(row.name)}</h3><p class="hint">此输出源已删除。已有配置和成本源保留，恢复后可重新选用。</p><button id="source-restore" class="primary">恢复输出源</button>`;$('#source-restore').onclick=()=>toggleDeleted(row,false);list();return;}const references=api.getConfigs().filter(c=>!c.deletedAt&&c.parts.some(p=>p.sourceId===row.sourceId)).length;
 $('#source-detail').innerHTML=`<div class="source-detail-heading"><h3>${selectedId?'编辑配件资料':'新增输出源配件'}</h3><span>${references} 套本店配置引用</span></div><div class="inline-grid"><label class="field">ERP ID<input id="source-id" value="${esc(row.goodsId)}" ${selectedId?'readonly':''} inputmode="numeric"></label><label class="field">ERP 单价（只读缓存）<input readonly value="${row.erp==null?'暂无':Number(row.erp).toFixed(2)}"></label></div><label class="field">本店产品显示名称<textarea id="source-name" rows="2">${esc(row.name)}</textarea></label><label class="field">三店共用含税核算单价<input id="source-tax" type="number" min="0" step=".01" value="${row.tax??''}" placeholder="留空表示待核算"></label><label class="field">本店升级文案<textarea id="source-upgrade" rows="2" placeholder="例如：+199 元升级…">${esc(row.upgrade)}</textarea></label><section class="source-addon-editor"><h4>三店加购</h4><div id="source-addon-fields"></div></section><small class="hint">更新时间：${row.updatedAt?new Date(row.updatedAt).toLocaleString():'尚未人工维护'}</small><div class="source-save-actions"><button id="source-reset">重置修改</button><button id="source-save" class="primary">保存输出源与勾选店铺加购</button></div><div class="source-bottom-actions"><button id="source-delete" class="danger" ${selectedId?'':'disabled'}>删除输出源</button></div>`;
 addonFields=mountShopAddons($('#source-addon-fields'),{original:{...draft,shopId:draft.shopId||api.shopId()},getRows:api.getAllRows,getCosts:api.getCosts,getOriginal:()=>({...draft,goodsId:$('#source-id').value.trim(),tax:$('#source-tax').value===''?null:Number($('#source-tax').value)}),onChange:invalidate});
 $('#source-delete').onclick=()=>{if(confirm(`删除“${row.name}”？已有配置和成本源保留，可以从“已删除”中恢复。`))return toggleDeleted(row,true);};
 $('#source-save').onclick=()=>{try{return commit(read(),[],[]);}catch(e){message(e.message);}};
 $('#source-reset').onclick=()=>{select(selectedId?api.getRows().find(r=>r.sourceId===selectedId):{sourceId:crypto.randomUUID(),goodsId:'',name:'',erp:null,tax:null,warranty:'质保',upgrade:'',addonText:'',addonNote:''});message('已重置未保存的修改');};
 $$('#source-detail input[id^="source-"],#source-detail textarea[id^="source-"],#source-detail select[id^="source-"]').forEach(el=>el.oninput=()=>{invalidate();addonFields.refresh();});
 list();}
 async function toggleDeleted(row,deleted){if(busy)return;busy=true;try{await api.setDeleted(row.sourceId,deleted);if(!$('#source-detail'))return;draft=null;selectedId=null;showDeleted=false;$('#source-deleted').textContent='已删除';const first=filtered()[0];if(first)select(first);else{$('#source-detail').innerHTML='<p class="hint">暂无输出源，可新增或从“已删除”恢复。</p>';list();}message(deleted?'输出源已删除，已有配置保留。':'输出源已恢复。');}catch(e){if($('#source-message'))message(e.message);}finally{busy=false;}}
 $('#source-addon-check').onclick=()=>{if(draft&&isEdited()){message('请先保存或重置当前修改，再检查全部输出源。');return;}const rows=api.getRows().filter(r=>!r.deletedAt),checks=rows.flatMap(row=>sourceAddonOptions(row).filter(a=>a.text?.trim()).map(addon=>({row,addon,result:addonCheck(addon,api.getCosts(),[row])}))),counts=checks.reduce((a,x)=>(a[x.result.severity]=(a[x.result.severity]||0)+1,a),{});$('#source-addon-report').innerHTML=`<p class="hint">共 ${checks.length} 项加购：需要调整 ${counts.danger||0}，核算负差价（未同时红色）${counts.warning||0}，核算待补充 ${counts.pending||0}，核算正常 ${counts.ok||0}。</p>`+checks.sort((a,b)=>({danger:0,warning:1,pending:2,ok:3}[a.result.severity]-{danger:0,warning:1,pending:2,ok:3}[b.result.severity])).map(({row,addon})=>`<div class="addon-audit-row"><strong>${esc(row.name)}</strong><p>${esc(addon.text)}</p>${addonStatusHtml(addon,api.getCosts(),[row])}<button data-addon-source="${esc(row.sourceId)}">编辑此加购</button></div>`).join('');$$('[data-addon-source]').forEach(b=>b.onclick=()=>{if(draft&&isEdited()){message('请先保存或重置当前修改。');return;}showDeleted=false;$('#source-deleted').textContent='已删除';select(api.getRows().find(r=>r.sourceId===b.dataset.addonSource));$('#source-detail').scrollIntoView({block:'start'});});};
 $('#source-deleted').onclick=()=>{if(busy)return;if(draft&&isEdited()){message('请先保存或重置当前修改。');return;}showDeleted=!showDeleted;page=0;draft=null;selectedId=null;$('#source-deleted').textContent=showDeleted?'返回在用':'已删除';const first=filtered()[0];if(first)select(first);else{$('#source-detail').innerHTML='<p class="hint">没有记录。</p>';list();}};
 $('#source-search').oninput=()=>{page=0;list();};$('#source-prev').onclick=()=>{page--;list();};$('#source-next').onclick=()=>{page++;list();};$('#source-new').onclick=()=>{if(busy)return;if(draft&&isEdited()){message('请先保存当前配件，或点击“重置修改”。');return;}showDeleted=false;$('#source-deleted').textContent='已删除';select({sourceId:crypto.randomUUID(),goodsId:'',name:'',erp:null,tax:null,warranty:'质保',upgrade:'',addonText:'',addonNote:''});};list();if(filtered().length)select(filtered()[0]);
}
