const esc=value=>String(value??'未知').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function bindSqlSync(api){
 const request=async(path,data)=>{const response=await fetch('/api/sql-sync/'+path,data===undefined?{signal:AbortSignal.timeout(15000)}:{...(path==='preview'?{signal:AbortSignal.timeout(90000)}:{}),method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'数据库服务不可用');return result;};
 let settings={server:'',port:1433,database:'',user:'',encrypt:true,trustServerCertificate:false};
 function setup(){
  settings={server:'',port:1433,database:'',user:'',encrypt:true,trustServerCertificate:false};
  api.openDialog('ERP同步 · 公司数据库',`<p class="hint">按 goods_id 精确匹配公司大库的分库可销数。先读取差异，再确认应用。同时读取“库存成本”作为单件 ERP 成本，保留人工核算价；ERP 成本与可销数仅保存在本机。读取时自动在本机加密保存账号和密码，下次打开自动填入；只供当前 Windows 用户及工作台成员使用，不上传云端。</p><form id="sql-connection-form"><div class="form-grid">${[['server','服务器'],['port','端口'],['database','数据库'],['user','只读账号']].map(([key,label])=>`<label class="field">${label}<input id="sql-${key}" name="${key}" value="${esc(settings[key])}" required ${key==='port'?'type="number" min="1" max="65535"':'autocomplete="off"'}></label>`).join('')}<label class="field">密码<input id="sql-password" type="password" autocomplete="off" required></label></div><label><input id="sql-encrypt" type="checkbox" ${settings.encrypt?'checked':''}> 加密连接</label> <label><input id="sql-trust" type="checkbox" ${settings.trustServerCertificate?'checked':''}> 信任服务器证书（公司自签证书时使用）</label><label style="display:block;margin-top:10px"><input id="sql-remember" type="checkbox" checked> 在本机加密保存并自动填入</label><button id="sql-forget" type="button">清除本机保存的连接</button><p id="sql-message" role="status" class="hint"></p><div class="actions"><button type="button" id="sql-cancel">取消</button><button type="submit" class="primary" id="sql-read" disabled>读取并预览</button></div></form>`);
  const form=document.querySelector('#sql-connection-form');let formEdited=false;form.addEventListener('input',()=>{formEdited=true;});
  request('credentials').then(saved=>{if(!form.isConnected||formEdited)return;if(saved.saved){settings=saved.settings;for(const key of ['server','port','database','user'])form.querySelector('#sql-'+key).value=settings[key];form.querySelector('#sql-encrypt').checked=settings.encrypt;form.querySelector('#sql-trust').checked=settings.trustServerCertificate;form.querySelector('#sql-password').value=saved.password;form.querySelector('#sql-message').textContent='已从本机加密存储填入连接信息';}}).catch(error=>{if(form.isConnected)form.querySelector('#sql-message').textContent=error.message;}).finally(()=>{if(form.isConnected)form.querySelector('#sql-read').disabled=false;});
  form.querySelector('#sql-forget').onclick=async()=>{try{await request('forget',{});if(!form.isConnected)return;formEdited=true;for(const key of ['server','database','user','password'])form.querySelector('#sql-'+key).value='';form.querySelector('#sql-remember').checked=false;form.querySelector('#sql-message').textContent='已清除本机保存的连接';}catch(e){form.querySelector('#sql-message').textContent=e.message;}};
  document.querySelector('#sql-cancel').onclick=()=>document.querySelector('#dialog').close();
  form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('#sql-read'),message=form.querySelector('#sql-message');button.disabled=true;message.textContent='正在保存本机配置…';let password=form.querySelector('#sql-password').value;form.querySelector('#sql-password').value='';
   try{await api.flush();message.textContent='正在连接 SQL 并读取 ERP 成本与库存，最多等待 90 秒…';settings={...Object.fromEntries(['server','port','database','user'].map(k=>[k,form.querySelector('#sql-'+k).value])),encrypt:form.querySelector('#sql-encrypt').checked,trustServerCertificate:form.querySelector('#sql-trust').checked};const result=await request('preview',{settings,password,remember:form.querySelector('#sql-remember').checked,operator:api.operator()});password='';if(!form.isConnected)return;showPreview(result);}catch(error){if(form.isConnected){form.querySelector('#sql-password').value=password;message.textContent=error.name==='TimeoutError'?'SQL 读取超时，尚未应用数据。请检查当前电脑的网络和 SQL 连接设置后重试。':error.message;button.disabled=false;}password='';}};
 }
 function showPreview(plan){
  api.openDialog('确认 ERP 成本与库存差异',`<p>来源：${esc(plan.source.server)}:${esc(plan.source.port)} / ${esc(plan.source.database)} · 公司大库</p><p>读取 ${plan.total} 件商品；匹配 ${plan.matched} 处记录，未匹配 ${plan.unmatched} 处，成本或库存变化 ${plan.changes.length} 处。</p><p class="hint">${plan.unknown} 件商品没有已确认的公司大库库存，将显示为未知；未匹配记录保留旧缓存，但配置价格计算会改用核算成本并显示警示。ERP 成本取自 SQL 库存成本；人工核算价保留，结果仅保存在本机。预览有效期 10 分钟。</p><div class="sql-diff-scroll"><table class="sql-diff-table"><colgroup><col style="width:70px"><col style="width:95px"><col><col style="width:145px"><col style="width:145px"></colgroup><thead><tr><th>位置</th><th>goods_id</th><th>配件</th><th>原可销数 / 成本</th><th>新可销数 / 成本</th></tr></thead><tbody>${plan.changes.slice(0,100).map(c=>`<tr><td>${esc(c.area)}</td><td>${esc(c.goodsId)}</td><td>${esc(c.name)}</td><td>${esc(c.before)} / ¥${esc(c.erpBefore)}</td><td>${esc(c.after)} / ¥${esc(c.erpAfter)}</td></tr>`).join('')}</tbody></table></div><div class="actions"><button id="sql-diff-prev">上一页</button><span id="sql-diff-page"></span><button id="sql-diff-next">下一页</button></div><p id="sql-apply-message" class="hint" role="status"></p><div class="actions"><button id="sql-preview-cancel">取消</button><button id="sql-apply" class="primary">确认应用</button></div>`);
  let diffPage=0;const drawDiff=()=>{const pages=Math.max(1,Math.ceil(plan.changes.length/100));document.querySelector('.sql-diff-table tbody').innerHTML=plan.changes.slice(diffPage*100,(diffPage+1)*100).map(c=>`<tr><td>${esc(c.area)}</td><td>${esc(c.goodsId)}</td><td>${esc(c.name)}</td><td>${esc(c.before)} / ¥${esc(c.erpBefore)}</td><td>${esc(c.after)} / ¥${esc(c.erpAfter)}</td></tr>`).join('');document.querySelector('#sql-diff-page').textContent=`第 ${diffPage+1} / ${pages} 页，共 ${plan.changes.length} 处变化`;document.querySelector('#sql-diff-prev').disabled=diffPage===0;document.querySelector('#sql-diff-next').disabled=diffPage>=pages-1;document.querySelector('.sql-diff-scroll').scrollTop=0;};document.querySelector('#sql-diff-prev').onclick=()=>{diffPage--;drawDiff();};document.querySelector('#sql-diff-next').onclick=()=>{diffPage++;drawDiff();};drawDiff();
  document.querySelector('#sql-preview-cancel').onclick=()=>document.querySelector('#dialog').close();document.querySelector('#sql-apply').onclick=async event=>{const button=event.currentTarget,message=document.querySelector('#sql-apply-message');button.disabled=true;try{await api.flush();const result=await request('apply',{id:plan.id});document.querySelector('#dialog').close();await api.receive(result);api.toast(`本机 ERP 成本与库存已更新：${plan.changes.length} 处变化，ERP 成本取自 SQL 库存成本；人工核算价保留，结果仅保存在本机。`);}catch(error){message.textContent=error.message;button.disabled=false;}};
 }
 return{setup,preview:setup};
}
