import cloudbase from './vendor/cloudbase.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let csrf,auth,records=[],active=null,dirty=false,paused=false,editingSnapshot=null;
const notice=error=>{$('#notice').textContent=error?.message||String(error||'');};
async function api(action,data){const r=await fetch('/api/cloud-sync/'+action,{method:data===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-DIY-Sync':csrf},...(data===undefined?{}:{body:JSON.stringify(data)})});const j=await r.json();if(!r.ok)throw Error(j.error||'请求失败');return j;}
function showStatus(s){paused=s.offline;$('#pause').textContent=paused?'恢复同步':'暂停同步';$('#login-panel').hidden=s.signedIn;$('#status').textContent=`${s.signedIn?s.member.name:'未登录'} · ${s.offline?'已暂停':s.running?'正在同步':s.lastError?'连接待恢复':s.conflicts?'存在冲突':s.pending?'本地已保存':s.lastSyncedAt?'已与云端同步':'等待连接'}\n待提交 ${s.pending} 项 · 冲突 ${s.conflicts} 项${s.uncertain?' · 有提交结果待确认':''}${s.lastError?'\n'+s.lastError:''}`;$('#sync').disabled=!s.signedIn||paused;}
function renderList(){ $('#count').textContent=`${records.length} 条`;$('#records').innerHTML=records.length?records.map((r,i)=>`<button class="record ${active===r.id?'active':''}" data-index="${i}"><strong>${esc(r.draft?.name||r.id)} ${r.draft?.deletedAt?'· 已回收':''}</strong><small>${r.type==='component'?'三店共享含税成本':'商品配置'} · 版本 ${r.version} ${r.conflict?'<span class="badge">需要处理冲突</span>':''}</small></button>`).join(''):'<p>登录后添加测试配置，或等待另一台电脑的更新。</p>';for(const b of $('#records').querySelectorAll('button'))b.onclick=()=>{if(dirty){notice('请先保存当前本地草稿，再切换记录。');return;}active=records[Number(b.dataset.index)].id;renderList();renderEditor();};}
function current(){return records.find(r=>r.id===active);}
function renderEditor(){const r=current();$('#editor').hidden=!r;$('#editor-empty').hidden=!!r;if(!r)return;editingSnapshot=structuredClone(r.draft);const f=$('#editor');f.elements.name.value=r.draft.name||'';const amount=r.type==='component'?r.draft.taxCents:r.draft.priceCents;f.elements.amount.value=amount==null?'':amount/100;f.elements.amount.required=r.type!=='component';f.elements.amount.placeholder=r.type==='component'?'留空表示缺少成本':'';f.elements.note.value=r.draft.note||'';f.elements.shopId.value=r.draft.shopId||'intel';$('#shop-field').hidden=r.type==='component';$('#record-meta').textContent=r.type==='component'?`共享范围：英特尔、技嘉、乔思伯 · ERP ID ${r.draft.goodsId}`:`配置 ID ${r.id}`;$('#delete').textContent=r.draft.deletedAt?'恢复记录':'移入回收状态';$('#draft-status').textContent='本地已保存';renderConflict(r);}
const fieldName=k=>({name:'名称',note:'备注',priceCents:'售价',taxCents:'含税成本',parts:'配件组合',shopId:'店铺','$record':'记录状态'}[k]||k);
function conflictValue(data,key){if(key==='$record')return data?`${data.name||''} · ${data.deletedAt?'已回收':'有效'}`:'不存在';const v=data?.[key];if(v==null)return '未填写';if(key==='priceCents'||key==='taxCents')return (v/100).toFixed(2)+' 元';if(key==='parts')return v.map(p=>`${p.name||p.goodsId} × ${p.qty}`).join('；');if(key==='shopId')return {intel:'英特尔',gigabyte:'技嘉',jonsbo:'乔思伯'}[v]||v;return typeof v==='object'?JSON.stringify(v):String(v);}
function renderConflict(r){const c=r.conflict;$('#conflicts').innerHTML=c?`<section><h2>这条记录需要选择</h2><p>冲突字段：${esc(c.fields.map(fieldName).join('、'))}。其他记录可继续同步。</p><div class="conflict-table"><table><thead><tr><th>字段</th><th>原值</th><th>我的修改</th><th>云端修改</th></tr></thead><tbody>${c.fields.map(k=>`<tr><th>${esc(fieldName(k))}</th><td>${esc(conflictValue(c.base,k))}</td><td>${esc(conflictValue(r.draft,k))}</td><td>${esc(conflictValue(c.remote.data,k))}</td></tr>`).join('')}</tbody></table></div><div class="buttons"><button data-choice="local">采用我的修改</button><button data-choice="remote">采用云端修改</button></div></section>`:'';for(const b of $('#conflicts').querySelectorAll('button'))b.onclick=()=>guard(async()=>{if(dirty)throw Error('请先保存本地草稿');await api('resolve',{type:r.type,id:r.id,choice:b.dataset.choice});await refresh(true);});}
async function refresh(force=false){const j=await api('records');records=j.records;showStatus(j.status);renderList();if(!dirty&&(force||!document.querySelector('#editor:focus-within')))renderEditor();}
async function guard(fn){try{notice('');await fn();}catch(e){notice(e);}}
$('#login').onsubmit=e=>{e.preventDefault();guard(async()=>{const f=e.target;const {error}=await auth.signInWithPassword({username:f.elements.username.value.trim(),password:f.elements.password.value});if(error)throw error;f.elements.password.value='';const {data}=await auth.getSession();if(!data?.session||data.session.user?.is_anonymous)throw Error('未获得有效成员会话');await api('session',{accessToken:data.session.access_token});await refresh(true);});};
$('#logout').onclick=()=>guard(async()=>{await auth?.signOut();await api('logout',{});await refresh();});
$('#sync').onclick=()=>guard(async()=>{await api('run',{});await refresh();});
$('#pause').onclick=()=>guard(async()=>{await api('pause',{paused:!paused});await refresh();});
$('#editor').oninput=()=>{dirty=true;$('#draft-status').textContent='尚未保存 · 云端更新不会覆盖当前输入';};
$('#editor').onsubmit=e=>{e.preventDefault();guard(async()=>{const r=current(),f=e.target,data=structuredClone(editingSnapshot),cents=f.elements.amount.value===''?null:Math.round(Number(f.elements.amount.value)*100);data.name=f.elements.name.value.trim();data.note=f.elements.note.value;if(r.type==='component')data.taxCents=cents;else{data.priceCents=cents;data.shopId=f.elements.shopId.value;}await api('edit',{type:r.type,id:r.id,data,expectedDraft:editingSnapshot});dirty=false;await refresh(true);});};
$('#reload-draft').onclick=()=>guard(async()=>{const f=$('#editor'),draft={record:editingSnapshot,inputs:Object.fromEntries(new FormData(f))},url=URL.createObjectURL(new Blob([JSON.stringify(draft,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='未保存的表单_'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);dirty=false;await refresh(true);});
$('#delete').onclick=()=>guard(async()=>{if(dirty)throw Error('请先保存本地草稿');const r=current(),data=structuredClone(r.draft);if(data.deletedAt)delete data.deletedAt;else data.deletedAt=new Date().toISOString();await api('edit',{type:r.type,id:r.id,data});await refresh(true);});
$('#add').onclick=()=>guard(async()=>{if(dirty)throw Error('请先保存当前本地草稿');const id=crypto.randomUUID();await api('edit',{type:'configuration',id,data:{id,name:'合成测试配置',shopId:'intel',priceCents:669900,note:'仅用于同步验收',parts:[{lineId:crypto.randomUUID(),slot:'CPU',goodsId:'999000001',qty:1,name:'测试 CPU'}]}});if(!records.some(r=>r.type==='component'&&r.id==='synthetic-test-only|999000001'))await api('edit',{type:'component',id:'synthetic-test-only|999000001',data:{name:'合成测试成本',goodsId:'999000001',erpScopeId:'synthetic-test-only',taxCents:140000}});active=id;await refresh(true);});
$('#history').onclick=()=>guard(async()=>{const r=current(),j=await api('history',{type:r.type,id:r.id});$('#detail-title').textContent='云端记录历史';$('#detail-body').textContent=JSON.stringify(j.records,null,2);$('#detail').showModal();});$('#close-detail').onclick=()=>$('#detail').close();
$('#backup').onclick=()=>guard(async()=>{const data=await api('backup',{}),a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download='同步验证备份_'+data.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);});
$('#preview').onclick=()=>guard(async()=>{const p=await api('migration-preview');$('#detail-title').textContent='本机数据迁移预览（只读）';$('#detail-body').textContent=`配置 ${p.counts.configurations} 条 · 成本 ${p.counts.components} 条 · 模板 ${p.counts.templates} 条\n原始图片 ${p.counts.uniqueOriginalImageAddresses} 个地址，共被 ${p.counts.originalImageReferences} 条配置引用（按地址去重）\n\n${p.issues.map(i=>i.message||`${i.code} · ${i.id||''}`).join('\n')||'基础格式检查未发现问题'}\n\n尚未进入正式迁移阶段，本次没有上传任何业务数据。`;$('#detail').showModal();});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
await guard(async()=>{const r=await fetch('/api/cloud-sync/config'),j=await r.json();csrf=j.csrf;if(j.config){const app=cloudbase.init({...j.config,env:j.config.envId,auth:{persistSession:false,detectSessionInUrl:false}});auth=app.auth;auth.onAuthStateChange((event,session)=>{if(event==='TOKEN_REFRESHED'&&session?.access_token)api('session',{accessToken:session.access_token}).catch(notice);if(event==='SIGNED_OUT')api('logout',{}).catch(notice);});}else{$('#login button').disabled=true;notice('请先配置本机 CloudBase 环境。');}await refresh(true);});
setInterval(()=>refresh().catch(notice),5000);
