import {bindChangeHistory} from './change-history-ui.js';
import {bindVersionHistory} from './version-history-ui.js';
import {workspaceAuth,leaveWorkspace,lockWorkspace} from './workspace-auth.js';
export async function bindWorkspaceSync({getState,flush,receive,openDialog,esc,toast,onMember}){
 let status={},busy=false,actionError='',receivedRevision=null;const button=document.querySelector('#workspace-sync'),label=document.querySelector('#workspace-sync-status');
 const {api}=await workspaceAuth();const history=bindVersionHistory({flush,receive,openDialog,esc,toast});const changes=bindChangeHistory({api,flush,openDialog,esc,toast});
 function paintNotice(){const notice=document.querySelector('#cloud-notice');if(!notice)return;const message=String(actionError||status.lastError||'').trim();notice.textContent=message;notice.hidden=!message;}
 const guard=fn=>async()=>{try{await fn();actionError='';paintNotice();}catch(e){actionError=e.message;toast(e.message);paintNotice();}};
 function paint(){paintNotice();label.textContent=!status.enabled?'尚未启用':!status.signedIn?'请登录':status.paused?'已暂停':status.running?(status.progress?.phase==='download'?`云端下载 ${status.progress.cursor} / ${status.progress.total}`:`同步中 · 待提交 ${status.pending}`):status.lastError?'等待重试':status.conflicts?`${status.conflicts} 项冲突`:status.pending?`待同步 ${status.pending} 项`:!status.lastSyncedAt?'本地就绪':'已同步';const progress=document.querySelector('#cloud-progress');if(progress)progress.textContent=label.textContent+` · 待提交 ${status.pending} 项 · 冲突 ${status.conflicts} 项`;label.title=status.lastError||'编辑自动保存在本机；云端每 2 小时同步一次，也可点击立即同步';}
 async function refresh(){status=await api('status');paint();if(!status.signedIn){await lockWorkspace();status=await api('status');paint();}onMember(status.member);if(status.enabled&&!status.running&&status.workspaceRevision!==receivedRevision){const received=await receive();if(received!==false)receivedRevision=status.workspaceRevision;}}
 async function panel(){actionError='';await refresh();
  const login=`<p>当前成员：${esc(status.member?.name)}</p><div class="actions"><button id="cloud-switch" class="primary">切换账号</button><button id="cloud-logout">退出登录</button></div><p class="hint">退出后返回登录页，本机数据保留。切换前请完成当前账号的同步。</p>`;
  openDialog('多人同步',`${login}<p id="cloud-notice" class="error" role="alert" ${String(status.lastError||'').trim()?'':'hidden'}>${esc(status.lastError||'')}</p><p>配置、人工核算价、店铺设置、模板、输出源和机箱图库在成员之间同步。ERP 成本和可销数仅保存在本机，由每位成员通过“ERP同步”读取；生成图和 ZIP 也保存在本机。</p><p class="hint">编辑与图片处理优先在本机完成。云端每 2 小时同步一次；点击“立即同步”可马上上传和接收更新，暂停自动同步时也可使用。</p><p id="cloud-progress">${esc(label.textContent)} · 待提交 ${status.pending} 项 · 冲突 ${status.conflicts} 项</p><div class="actions">${status.enabled?'<button id="cloud-now" class="primary">立即同步</button><button id="cloud-pause">'+(status.paused?'恢复自动同步':'暂停自动同步')+'</button><button id="cloud-conflicts">处理冲突</button>':'<button id="cloud-preview" class="primary">预览并发布本机数据</button><button id="cloud-join">接收已有云端数据</button>'}<button id="cloud-backup">下载同步备份</button><button id="cloud-history">历史版本</button>${status.changeHistory?'<button id="cloud-changes">修改与提交记录</button>':''}<a href="/cloudbase-maintenance.html" target="_blank">CloudBase 维护说明</a></div><p class="hint">库存来源保留“公司数据库”和“脚本抓取”两种方式。公司数据库在顶部“连接设置”中配置并预览库存差异。</p>`);
  const leave=guard(async()=>{await flush();for(const id of ['cloud-switch','cloud-logout'])document.getElementById(id).disabled=true;try{await leaveWorkspace();}catch(error){for(const id of ['cloud-switch','cloud-logout'])document.getElementById(id).disabled=false;throw error;}});
  document.querySelector('#cloud-switch').addEventListener('click',leave);
  document.querySelector('#cloud-history').onclick=history.open;document.querySelector('#cloud-changes')?.addEventListener('click',changes.open);
  document.querySelector('#cloud-logout').addEventListener('click',leave);
  document.querySelector('#cloud-now')?.addEventListener('click',guard(async()=>{await flush();await api('run',{});await refresh();toast('已开始同步，可继续编辑');}));
  document.querySelector('#cloud-pause')?.addEventListener('click',guard(async()=>{await api('pause',{paused:!status.paused});await panel();}));
  document.querySelector('#cloud-join')?.addEventListener('click',guard(async()=>{await flush();openDialog('接收云端工作台','<p>当前本机数据会先自动备份，完整下载后切换为云端数据。原始图片会按需下载到本地。</p><button id="cloud-join-confirm" class="primary">备份本机并接收</button>');document.querySelector('#cloud-join-confirm').onclick=guard(async()=>{await api('enable',{mode:'join'});await panel();});}));
  document.querySelector('#cloud-preview')?.addEventListener('click',guard(async()=>{await flush();const p=await api('preview');openDialog('首次同步迁移预览',`<p>配置 ${p.counts.configuration||0} 条，人工核算价 ${p.counts.component||0} 条，输出源 ${p.counts.source||0} 条，模板 ${p.counts.template||0} 条，图库 ${p.counts.gallery||0} 条。</p><p>售价已完成往返换算校验；发布前自动备份本机数据。</p>${p.issues.length?`<p class="error">${p.issues.length} 项待处理</p><pre>${esc(JSON.stringify(p.issues.slice(0,20),null,2))}</pre>`:'<button id="cloud-publish" class="primary">确认发布并启用同步</button>'}`);document.querySelector('#cloud-publish')?.addEventListener('click',guard(async()=>{await api('enable',{mode:'publish',previewHash:p.hash});await panel();}));}));
  document.querySelector('#cloud-conflicts')?.addEventListener('click',guard(async()=>{const {records}=await api('conflicts');openDialog('同步冲突',records.length?records.map((r,i)=>`<section class="list-card"><div><strong>${esc(r.draft.name||r.id)}</strong><p>冲突字段：${esc(r.conflict.fields.join('、'))}</p><details><summary>查看原值、我的修改和云端修改</summary><pre>${esc(JSON.stringify({基础:r.conflict.base,我的:r.draft,云端:r.conflict.remote.data},null,2))}</pre></details><button data-conflict="${i}" data-choice="local">采用我的修改</button> <button data-conflict="${i}" data-choice="remote">采用云端修改</button></div></section>`).join(''):'<p>没有待处理冲突。</p>');for(const b of document.querySelectorAll('[data-conflict]'))b.onclick=guard(async()=>{await flush();const r=records[Number(b.dataset.conflict)];await api('resolve',{type:r.type,id:r.id,choice:b.dataset.choice});await receive();await panel();});}));
  document.querySelector('#cloud-backup')?.addEventListener('click',guard(async()=>{const b=await api('backup',{}),u=URL.createObjectURL(new Blob([JSON.stringify(b)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='工作台同步备份_'+b.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),10000);}));
 }
 const open=guard(async()=>{await flush();await panel();});
 window.addEventListener('workspace-auth-error',event=>{label.textContent='登录状态需重新验证';label.title=event.detail;toast(event.detail);lockWorkspace().catch(error=>toast(error.message));});
 try{button.onclick=open;await refresh();setInterval(async()=>{if(busy)return;busy=true;try{await refresh();}catch(error){actionError=error.message;label.textContent='同步状态读取失败';label.title=error.message;paintNotice();}finally{busy=false;}},5000);}catch(e){label.textContent='同步暂不可用';label.title=e.message;}

 return {status:()=>status,open};
}
