// ==UserScript==
// @name         DIY 工作台库存与 ERP 成本同步
// @namespace    local.diy.workbench
// @version      0.1.0
// @description  响应本机工作台一键同步，只读公司大库库存和成本，不修改 ERP
// @match        https://cqzs.3cerp.com/*
// @grant        GM_xmlhttpRequest
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_registerMenuCommand
// @grant        unsafeWindow
// @connect      127.0.0.1
// @noframes
// @run-at       document-idle
// ==/UserScript==
(function(){
 'use strict';
 // Pagination, stock semantics and identity checks adapted from
 // 后台库存监控/inventory-erp.user.js 0.4.0; original monitor is not modified.
 async function collectPages(fetchPage){let rows=[],expected=null;for(let page=0;page<500;page++){const result=await fetchPage(page);if(!result||result.result===false||result.success===false||result.st!==undefined&&result.st!==0)throw Error('ERP 未返回有效库存');const data=result.data||result.rows||result.list,total=Number(result.total);if(!Array.isArray(data)||result.total===undefined||!Number.isInteger(total)||total<0)throw Error('库存分页数据不完整');if(expected===null)expected=total;if(expected!==total)throw Error('分页期间总数变化，请重试');rows.push(...data);if(rows.length===expected)return rows;if(!data.length||rows.length>expected)throw Error('库存分页数量不一致');}throw Error('分页超过上限');}
 function numeric(value,label){if(value===null)return null;if(value===undefined||typeof value==='string'&&!value.trim()||!['number','string'].includes(typeof value)||!Number.isFinite(Number(value)))throw Error(label+'字段缺失或无效');return Number(value);}
 function normalizeRows(rows,costField){const seen=new Set();return rows.map(row=>{const goodsId=String(row.goods_id||'');if(!/^\d{1,20}$/.test(goodsId)||goodsId==='0'||seen.has(goodsId))throw Error('商品 ID 缺失或重复');seen.add(goodsId);const name=String(row.b_c_name||'').trim();if(!name)throw Error('商品名称缺失');const erp=numeric(row[costField],'ERP 成本');if(erp!==null&&erp<0)throw Error('ERP 成本为负数');return{goodsId,name,stockAvailable:numeric(row.n_stock_able,'可销库存'),erp};});}
 if(typeof module==='object'&&module.exports){module.exports={collectPages,normalizeRows};return;}
 if(window.top!==window.self)return;
 const pageWindow=typeof unsafeWindow!=='undefined'?unsafeWindow:window;
 const clientId=crypto.randomUUID();let busy=false;
 const badge=document.createElement('button');badge.textContent='工作台同步：点击连接';Object.assign(badge.style,{position:'fixed',right:'18px',bottom:'80px',zIndex:2147483000,padding:'10px 14px',border:'1px solid #8bbef7',borderRadius:'8px',background:'#edf5ff',color:'#164570',cursor:'pointer'});document.body.append(badge);
 function frames(win=pageWindow,depth=0){const out=[win];if(depth<6)for(const f of win.document.querySelectorAll('iframe'))try{if(f.contentWindow.document)out.push(...frames(f.contentWindow,depth+1));}catch{}return out;}
 function warehouse(){const values=[];for(const win of frames()){for(const select of win.document.querySelectorAll('select')){const option=select.selectedOptions?.[0];if(option?.textContent.trim()==='公司大库'&&/^\d+$/.test(option.value))values.push(option.value);}if(win.mini)for(const id of ['depot_id','depotIds','depotId'])try{const control=win.mini.get(id);if(control&&control.getText().trim()==='公司大库'&&/^\d+$/.test(String(control.getValue())))values.push(String(control.getValue()));}catch{}}const unique=[...new Set(values)];if(unique.length!==1)throw Error('请打开分库库存并选择公司大库');return unique[0];}
 function accountVisible(name){const header=document.querySelector('.topNav')||document.querySelector('.navbar');return !!header&&[...header.querySelectorAll('a,span')].some(el=>el.getClientRects().length&&el.innerText.trim()===name);}
 function costColumns(){const cols=[];const text=value=>{const div=document.createElement('div');div.innerHTML=String(value||'');return div.textContent.replace(/\s+/g,'').trim();};for(const win of frames()){if(!win.mini)continue;for(const el of win.document.querySelectorAll('.mini-datagrid'))try{const grid=win.mini.get(el.id);if(!grid?.getColumns)continue;const flatten=items=>items.flatMap(c=>c.columns?flatten(c.columns):[c]);const columns=flatten(grid.getColumns());if(!columns.some(c=>c.field==='n_stock_able'))continue;for(const c of columns){const header=text(c.header);if(c.field&&/成本/.test(header)&&!/金额|总|合计/.test(header))cols.push({field:c.field,header});}}catch{}}return [...new Map(cols.map(c=>[c.field,c])).values()];}
 function configure(){try{const depotId=warehouse();const account=prompt('请输入 ERP 顶栏显示的账号姓名（不是密码）');if(!account)return;if(!accountVisible(account.trim()))throw Error('ERP 顶栏未找到此账号');const columns=costColumns();if(!columns.length)throw Error('未识别到成本单价列，请在分库库存显示成本列后再连接');let index=0;if(columns.length>1){const value=prompt('选择 ERP 成本单价列编号：\n'+columns.map((c,i)=>`${i+1}. ${c.header}`).join('\n'));if(value===null)return;index=Number(value)-1;if(!Number.isInteger(index)||!columns[index])throw Error('列编号无效');}GM_setValue('diy_connection',{account:account.trim(),depotId,costField:columns[index].field,costHeader:columns[index].header});badge.textContent='工作台同步：已设置，等待连接';tick();}catch(e){alert(e.message);}}
 badge.onclick=configure;GM_registerMenuCommand('连接 DIY 工作台',configure);
 function local(path,data){return new Promise((resolve,reject)=>GM_xmlhttpRequest({method:'POST',url:'http://127.0.0.1:4178/api/erp-bridge/'+path,headers:{'Content-Type':'application/json','X-DIY-Collector':'workbench-erp-v1'},data:JSON.stringify(data),timeout:25000,onload:r=>{try{const j=JSON.parse(r.responseText);if(r.status!==200)throw Error(j.error||'工作台连接失败');resolve(j);}catch(e){reject(e);}},onerror:()=>reject(Error('请启动本机配置工作台')),ontimeout:()=>reject(Error('工作台连接超时'))}));}
 async function tick(){if(busy)return;busy=true;let identity,job;try{const config=GM_getValue('diy_connection',null);if(!config)return;if(warehouse()!==config.depotId||!accountVisible(config.account))throw Error('账号或仓库不匹配，请重新核对');identity={clientId,account:config.account,warehouse:'公司大库',depotId:config.depotId};const response=await local('poll',identity);job=response.job;if(!job){badge.textContent='工作台同步：已连接';return;}const columns=costColumns();if(!columns.some(c=>c.field===config.costField&&c.header===config.costHeader))throw Error('成本列发生变化，请重新连接');const credentials={...identity,jobId:job.id,token:job.token};const raw=await collectPages(async page=>{if(warehouse()!==config.depotId||!accountVisible(config.account))throw Error('采集期间账号或仓库变化');badge.textContent=`工作台同步：读取第 ${page+1} 页`;await local('progress',{...credentials,progress:`正在读取第 ${page+1} 页`});const body=new URLSearchParams({filter:'',depotIds:config.depotId,b_stock:'0',search_category:'',search_out_stock:'0',search_zero_stock:'0',pageSize:'2000',pageIndex:String(page),sortField:'',sortOrder:''});const result=await fetch('/pages/stock/searchDeoptStockList.htm',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8','X-Requested-With':'XMLHttpRequest'},body,signal:AbortSignal.timeout(30000)});if(!result.ok||result.redirected||!result.headers.get('content-type')?.includes('json'))throw Error('ERP 登录失效或库存请求失败');return result.json();});const rows=normalizeRows(raw,config.costField);if(warehouse()!==config.depotId||!accountVisible(config.account))throw Error('采集期间账号或仓库变化');await local('snapshot',{...credentials,complete:true,total:rows.length,costField:config.costField,rows});badge.textContent=`工作台同步：成功 ${rows.length} 条`;}catch(e){badge.textContent='工作台同步：'+e.message;if(identity&&job)await local('error',{...identity,jobId:job.id,token:job.token,error:e.message}).catch(()=>{});}finally{busy=false;}}
 setInterval(tick,5000);tick();
})();
